run:
  skip-files:
    - validator/web/site_data.go
    - .*_test.go
    - .*.pb.go
    - .*.yaml.go
  skip-dirs:
    - proto
    - tools/analyzers
  timeout: 10m
  go: '1.18'

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - unused
    - errcheck
    - gosimple
    - gocognit
    - govet

linters-settings:
  gocognit:
    # TODO: We should target for < 50
    min-complexity: 65
  govet:
    disable-all: true
    enable:
      - fieldalignment

output:
  print-issued-lines: true
  sort-results: true
