load("@prysm//tools/go:def.bzl", "go_test")

go_test(
    name = "go_default_test",
    size = "large",
    srcs = [
        "gloas__epoch_processing__effective_balance_updates_test.go",
        "gloas__epoch_processing__eth1_data_reset_test.go",
        "gloas__epoch_processing__historical_summaries_update_test.go",
        "gloas__epoch_processing__inactivity_updates_test.go",
        "gloas__epoch_processing__justification_and_finalization_test.go",
        "gloas__epoch_processing__participation_flag_updates_test.go",
        "gloas__epoch_processing__pending_consolidations_test.go",
        "gloas__epoch_processing__pending_deposits_churn_test.go",
        "gloas__epoch_processing__pending_deposits_test.go",
        "gloas__epoch_processing__process_builder_pending_payments_test.go",
        "gloas__epoch_processing__proposer_lookahead_test.go",
        "gloas__epoch_processing__randao_mixes_reset_test.go",
        "gloas__epoch_processing__registry_updates_test.go",
        "gloas__epoch_processing__rewards_and_penalties_test.go",
        "gloas__epoch_processing__slashings_reset_test.go",
        "gloas__epoch_processing__slashings_test.go",
        "gloas__finality__finality_test.go",
        "gloas__fork__upgrade_to_gloas_test.go",
        "gloas__fork_transition__transition_test.go",
        "gloas__forkchoice__forkchoice_test.go",
        "gloas__operations__attestation_test.go",
        "gloas__operations__attester_slashing_test.go",
        "gloas__operations__block_header_test.go",
        "gloas__operations__bls_to_execution_change_test.go",
        "gloas__operations__builder_deposit_request_test.go",
        "gloas__operations__builder_exit_request_test.go",
        "gloas__operations__consolidation_test.go",
        "gloas__operations__deposit_requests_test.go",
        "gloas__operations__execution_payload_header_test.go",
        "gloas__operations__parent_execution_payload_test.go",
        "gloas__operations__payload_attestation_test.go",
        "gloas__operations__proposer_slashing_test.go",
        "gloas__operations__sync_committee_test.go",
        "gloas__operations__voluntary_exit_churn_test.go",
        "gloas__operations__voluntary_exit_test.go",
        "gloas__operations__withdrawal_request_test.go",
        "gloas__operations__withdrawals_test.go",
        "gloas__random_test.go",
        "gloas__rewards_test.go",
        "gloas__sanity__blocks_test.go",
        "gloas__sanity__slots_test.go",
        "gloas__ssz_static__ssz_static_test.go",
    ],
    data = ["@consensus_spec_tests//:test_data"],
    tags = ["spectest"],
    deps = [
        "//runtime/version:go_default_library",
        "//testing/spectest/shared/common/forkchoice:go_default_library",
        "//testing/spectest/shared/gloas/epoch_processing:go_default_library",
        "//testing/spectest/shared/gloas/finality:go_default_library",
        "//testing/spectest/shared/gloas/fork:go_default_library",
        "//testing/spectest/shared/gloas/operations:go_default_library",
        "//testing/spectest/shared/gloas/rewards:go_default_library",
        "//testing/spectest/shared/gloas/sanity:go_default_library",
        "//testing/spectest/shared/gloas/ssz_static:go_default_library",
    ],
)
