// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prysmaticlabs/prysm/v4/validator/client/beacon-api (interfaces: BeaconBlockConverter)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	shared "github.com/prysmaticlabs/prysm/v4/beacon-chain/rpc/eth/shared"
	eth "github.com/prysmaticlabs/prysm/v4/proto/prysm/v1alpha1"
)

// MockBeaconBlockConverter is a mock of BeaconBlockConverter interface.
type MockBeaconBlockConverter struct {
	ctrl     *gomock.Controller
	recorder *MockBeaconBlockConverterMockRecorder
}

// MockBeaconBlockConverterMockRecorder is the mock recorder for MockBeaconBlockConverter.
type MockBeaconBlockConverterMockRecorder struct {
	mock *MockBeaconBlockConverter
}

// NewMockBeaconBlockConverter creates a new mock instance.
func NewMockBeaconBlockConverter(ctrl *gomock.Controller) *MockBeaconBlockConverter {
	mock := &MockBeaconBlockConverter{ctrl: ctrl}
	mock.recorder = &MockBeaconBlockConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBeaconBlockConverter) EXPECT() *MockBeaconBlockConverterMockRecorder {
	return m.recorder
}

// ConvertRESTAltairBlockToProto mocks base method.
func (m *MockBeaconBlockConverter) ConvertRESTAltairBlockToProto(arg0 *shared.BeaconBlockAltair) (*eth.BeaconBlockAltair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertRESTAltairBlockToProto", arg0)
	ret0, _ := ret[0].(*eth.BeaconBlockAltair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertRESTAltairBlockToProto indicates an expected call of ConvertRESTAltairBlockToProto.
func (mr *MockBeaconBlockConverterMockRecorder) ConvertRESTAltairBlockToProto(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertRESTAltairBlockToProto", reflect.TypeOf((*MockBeaconBlockConverter)(nil).ConvertRESTAltairBlockToProto), arg0)
}

// ConvertRESTBellatrixBlockToProto mocks base method.
func (m *MockBeaconBlockConverter) ConvertRESTBellatrixBlockToProto(arg0 *shared.BeaconBlockBellatrix) (*eth.BeaconBlockBellatrix, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertRESTBellatrixBlockToProto", arg0)
	ret0, _ := ret[0].(*eth.BeaconBlockBellatrix)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertRESTBellatrixBlockToProto indicates an expected call of ConvertRESTBellatrixBlockToProto.
func (mr *MockBeaconBlockConverterMockRecorder) ConvertRESTBellatrixBlockToProto(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertRESTBellatrixBlockToProto", reflect.TypeOf((*MockBeaconBlockConverter)(nil).ConvertRESTBellatrixBlockToProto), arg0)
}

// ConvertRESTCapellaBlockToProto mocks base method.
func (m *MockBeaconBlockConverter) ConvertRESTCapellaBlockToProto(arg0 *shared.BeaconBlockCapella) (*eth.BeaconBlockCapella, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertRESTCapellaBlockToProto", arg0)
	ret0, _ := ret[0].(*eth.BeaconBlockCapella)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertRESTCapellaBlockToProto indicates an expected call of ConvertRESTCapellaBlockToProto.
func (mr *MockBeaconBlockConverterMockRecorder) ConvertRESTCapellaBlockToProto(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertRESTCapellaBlockToProto", reflect.TypeOf((*MockBeaconBlockConverter)(nil).ConvertRESTCapellaBlockToProto), arg0)
}

// ConvertRESTPhase0BlockToProto mocks base method.
func (m *MockBeaconBlockConverter) ConvertRESTPhase0BlockToProto(arg0 *shared.BeaconBlock) (*eth.BeaconBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertRESTPhase0BlockToProto", arg0)
	ret0, _ := ret[0].(*eth.BeaconBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertRESTPhase0BlockToProto indicates an expected call of ConvertRESTPhase0BlockToProto.
func (mr *MockBeaconBlockConverterMockRecorder) ConvertRESTPhase0BlockToProto(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertRESTPhase0BlockToProto", reflect.TypeOf((*MockBeaconBlockConverter)(nil).ConvertRESTPhase0BlockToProto), arg0)
}
