{
 "title": "BlobWatcher Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Account", "query": { "query": "label_values(account)" } }
  ]
 },
 "panels": [
  {
   "title": "Blob Mempool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "viable_transaction", "legendFormat": "Viable Transactions" },
    { "expr": "viable_blobs", "legendFormat": "Viable Blobs" },
    {
     "expr": "increase(transaction_inclusion[20s])/increase(block_number[20s])",
     "legendFormat": "Transactions Included In Block"
    },
    {
     "expr": "increase(blob_inclusion[20s])/increase(block_number[20s])",
     "legendFormat": "Blobs Included In Block"
    }
   ]
  },
  {
   "title": "Blob Transaction Inclusion Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(transaction_inclusion_delay_sum{account=\"$Account\"}[30s])/increase(transaction_inclusion_delay_count{account=\"$Account\"}[30s])",
     "legendFormat": "$Account"
    }
   ]
  },
  {
   "title": "Blob Base Fee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "blob_base_fee", "legendFormat": "Blob Base Fee" }
   ]
  },
  {
   "title": "Transaction Blob Fee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(transactions_observed{account=\"$Account\"}[20s])",
     "legendFormat": "$Account-blobFee - {{maxBlobBaseFee}}"
    }
   ]
  }
 ]
}