load("@prysm//tools/go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "beacon_client.go",
        "log.go",
        "service.go",
    ],
    importpath = "github.com/OffchainLabs/prysm/v7/validator/client/optionalproofs",
    visibility = ["//visibility:public"],
    deps = [
        "//api:go_default_library",
        "//api/client/event:go_default_library",
        "//api/client/proofnode:go_default_library",
        "//api/server/structs:go_default_library",
        "//config/params:go_default_library",
        "//consensus-types/blocks:go_default_library",
        "//consensus-types/interfaces:go_default_library",
        "//consensus-types/primitives:go_default_library",
        "//proto/engine/v1:go_default_library",
        "//proto/prysm/v1alpha1:go_default_library",
        "//time/slots:go_default_library",
        "@com_github_ethereum_go_ethereum//common/hexutil:go_default_library",
        "@com_github_sirupsen_logrus//:go_default_library",
    ],
)
