package helpers

// export these for helpers_test package visibility.
var ErrWeakSubjectivityZeroValidators = errWeakSubjectivityZeroValidators
var ErrInvalidWeakSubjectivityState = errInvalidWeakSubjectivityState
var ErrWeakSubjectivityMismatchedRoot = errWeakSubjectivityMismatchedRoot
var ErrWeakSubjectivityMismatchedEpoch = errWeakSubjectivityMismatchedEpoch
