load("@prysm//tools/go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    testonly = True,
    srcs = [
        "config.go",
        "crypto_fake.go",  # keep
        "crypto_real.go",
        "utils.go",
    ],
    importpath = "github.com/OffchainLabs/prysm/v7/testing/spectest/utils",
    visibility = ["//testing/spectest:__subpackages__"],
    deps = [
        "//build/bazel:go_default_library",
        "//config/params:go_default_library",
        "//io/file:go_default_library",
        "//testing/require:go_default_library",
        "@com_github_ghodss_yaml//:go_default_library",
        "@com_github_json_iterator_go//:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    size = "small",
    srcs = [
        "config_test.go",
        "utils_test.go",
    ],
    embed = [":go_default_library"],
    deps = [
        "//config/params:go_default_library",
        "//consensus-types/primitives:go_default_library",
        "//testing/require:go_default_library",
    ],
)
