// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package ethereum_beacon_p2p_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Topic int32

const (
	Topic_UNKNOWN                             Topic = 0
	Topic_BEACON_BLOCK_HASH_ANNOUNCE          Topic = 1
	Topic_BEACON_BLOCK_REQUEST                Topic = 2
	Topic_BEACON_BLOCK_REQUEST_BY_SLOT_NUMBER Topic = 3
	Topic_BEACON_BLOCK_RESPONSE               Topic = 4
	Topic_CRYSTALLIZED_STATE_HASH_ANNOUNCE    Topic = 5
	Topic_CRYSTALLIZED_STATE_REQUEST          Topic = 6
	Topic_CRYSTALLIZED_STATE_RESPONSE         Topic = 7
	Topic_ACTIVE_STATE_HASH_ANNOUNCE          Topic = 8
	Topic_ACTIVE_STATE_REQUEST                Topic = 9
	Topic_ACTIVE_STATE_RESPONSE               Topic = 10
)

var Topic_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "BEACON_BLOCK_HASH_ANNOUNCE",
	2:  "BEACON_BLOCK_REQUEST",
	3:  "BEACON_BLOCK_REQUEST_BY_SLOT_NUMBER",
	4:  "BEACON_BLOCK_RESPONSE",
	5:  "CRYSTALLIZED_STATE_HASH_ANNOUNCE",
	6:  "CRYSTALLIZED_STATE_REQUEST",
	7:  "CRYSTALLIZED_STATE_RESPONSE",
	8:  "ACTIVE_STATE_HASH_ANNOUNCE",
	9:  "ACTIVE_STATE_REQUEST",
	10: "ACTIVE_STATE_RESPONSE",
}
var Topic_value = map[string]int32{
	"UNKNOWN":                             0,
	"BEACON_BLOCK_HASH_ANNOUNCE":          1,
	"BEACON_BLOCK_REQUEST":                2,
	"BEACON_BLOCK_REQUEST_BY_SLOT_NUMBER": 3,
	"BEACON_BLOCK_RESPONSE":               4,
	"CRYSTALLIZED_STATE_HASH_ANNOUNCE":    5,
	"CRYSTALLIZED_STATE_REQUEST":          6,
	"CRYSTALLIZED_STATE_RESPONSE":         7,
	"ACTIVE_STATE_HASH_ANNOUNCE":          8,
	"ACTIVE_STATE_REQUEST":                9,
	"ACTIVE_STATE_RESPONSE":               10,
}

func (x Topic) String() string {
	return proto.EnumName(Topic_name, int32(x))
}
func (Topic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{0}
}

type BeaconBlockHashAnnounce struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeaconBlockHashAnnounce) Reset()         { *m = BeaconBlockHashAnnounce{} }
func (m *BeaconBlockHashAnnounce) String() string { return proto.CompactTextString(m) }
func (*BeaconBlockHashAnnounce) ProtoMessage()    {}
func (*BeaconBlockHashAnnounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{0}
}
func (m *BeaconBlockHashAnnounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlockHashAnnounce.Unmarshal(m, b)
}
func (m *BeaconBlockHashAnnounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlockHashAnnounce.Marshal(b, m, deterministic)
}
func (dst *BeaconBlockHashAnnounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlockHashAnnounce.Merge(dst, src)
}
func (m *BeaconBlockHashAnnounce) XXX_Size() int {
	return xxx_messageInfo_BeaconBlockHashAnnounce.Size(m)
}
func (m *BeaconBlockHashAnnounce) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlockHashAnnounce.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlockHashAnnounce proto.InternalMessageInfo

func (m *BeaconBlockHashAnnounce) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type BeaconBlockRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeaconBlockRequest) Reset()         { *m = BeaconBlockRequest{} }
func (m *BeaconBlockRequest) String() string { return proto.CompactTextString(m) }
func (*BeaconBlockRequest) ProtoMessage()    {}
func (*BeaconBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{1}
}
func (m *BeaconBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlockRequest.Unmarshal(m, b)
}
func (m *BeaconBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlockRequest.Marshal(b, m, deterministic)
}
func (dst *BeaconBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlockRequest.Merge(dst, src)
}
func (m *BeaconBlockRequest) XXX_Size() int {
	return xxx_messageInfo_BeaconBlockRequest.Size(m)
}
func (m *BeaconBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlockRequest proto.InternalMessageInfo

func (m *BeaconBlockRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type BeaconBlockRequestBySlotNumber struct {
	SlotNumber           uint64   `protobuf:"varint,1,opt,name=slot_number,json=slotNumber,proto3" json:"slot_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeaconBlockRequestBySlotNumber) Reset()         { *m = BeaconBlockRequestBySlotNumber{} }
func (m *BeaconBlockRequestBySlotNumber) String() string { return proto.CompactTextString(m) }
func (*BeaconBlockRequestBySlotNumber) ProtoMessage()    {}
func (*BeaconBlockRequestBySlotNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{2}
}
func (m *BeaconBlockRequestBySlotNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlockRequestBySlotNumber.Unmarshal(m, b)
}
func (m *BeaconBlockRequestBySlotNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlockRequestBySlotNumber.Marshal(b, m, deterministic)
}
func (dst *BeaconBlockRequestBySlotNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlockRequestBySlotNumber.Merge(dst, src)
}
func (m *BeaconBlockRequestBySlotNumber) XXX_Size() int {
	return xxx_messageInfo_BeaconBlockRequestBySlotNumber.Size(m)
}
func (m *BeaconBlockRequestBySlotNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlockRequestBySlotNumber.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlockRequestBySlotNumber proto.InternalMessageInfo

func (m *BeaconBlockRequestBySlotNumber) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

type BeaconBlockResponse struct {
	Block                *BeaconBlock       `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Attestation          *AttestationRecord `protobuf:"bytes,2,opt,name=attestation,proto3" json:"attestation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BeaconBlockResponse) Reset()         { *m = BeaconBlockResponse{} }
func (m *BeaconBlockResponse) String() string { return proto.CompactTextString(m) }
func (*BeaconBlockResponse) ProtoMessage()    {}
func (*BeaconBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{3}
}
func (m *BeaconBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlockResponse.Unmarshal(m, b)
}
func (m *BeaconBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlockResponse.Marshal(b, m, deterministic)
}
func (dst *BeaconBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlockResponse.Merge(dst, src)
}
func (m *BeaconBlockResponse) XXX_Size() int {
	return xxx_messageInfo_BeaconBlockResponse.Size(m)
}
func (m *BeaconBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlockResponse proto.InternalMessageInfo

func (m *BeaconBlockResponse) GetBlock() *BeaconBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BeaconBlockResponse) GetAttestation() *AttestationRecord {
	if m != nil {
		return m.Attestation
	}
	return nil
}

type BeaconBlock struct {
	ParentHash            []byte               `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	SlotNumber            uint64               `protobuf:"varint,2,opt,name=slot_number,json=slotNumber,proto3" json:"slot_number,omitempty"`
	RandaoReveal          []byte               `protobuf:"bytes,3,opt,name=randao_reveal,json=randaoReveal,proto3" json:"randao_reveal,omitempty"`
	PowChainRef           []byte               `protobuf:"bytes,4,opt,name=pow_chain_ref,json=powChainRef,proto3" json:"pow_chain_ref,omitempty"`
	ActiveStateHash       []byte               `protobuf:"bytes,5,opt,name=active_state_hash,json=activeStateHash,proto3" json:"active_state_hash,omitempty"`
	CrystallizedStateHash []byte               `protobuf:"bytes,6,opt,name=crystallized_state_hash,json=crystallizedStateHash,proto3" json:"crystallized_state_hash,omitempty"`
	Timestamp             *timestamp.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Attestations          []*AttestationRecord `protobuf:"bytes,8,rep,name=attestations,proto3" json:"attestations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *BeaconBlock) Reset()         { *m = BeaconBlock{} }
func (m *BeaconBlock) String() string { return proto.CompactTextString(m) }
func (*BeaconBlock) ProtoMessage()    {}
func (*BeaconBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{4}
}
func (m *BeaconBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlock.Unmarshal(m, b)
}
func (m *BeaconBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlock.Marshal(b, m, deterministic)
}
func (dst *BeaconBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlock.Merge(dst, src)
}
func (m *BeaconBlock) XXX_Size() int {
	return xxx_messageInfo_BeaconBlock.Size(m)
}
func (m *BeaconBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlock.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlock proto.InternalMessageInfo

func (m *BeaconBlock) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BeaconBlock) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

func (m *BeaconBlock) GetRandaoReveal() []byte {
	if m != nil {
		return m.RandaoReveal
	}
	return nil
}

func (m *BeaconBlock) GetPowChainRef() []byte {
	if m != nil {
		return m.PowChainRef
	}
	return nil
}

func (m *BeaconBlock) GetActiveStateHash() []byte {
	if m != nil {
		return m.ActiveStateHash
	}
	return nil
}

func (m *BeaconBlock) GetCrystallizedStateHash() []byte {
	if m != nil {
		return m.CrystallizedStateHash
	}
	return nil
}

func (m *BeaconBlock) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *BeaconBlock) GetAttestations() []*AttestationRecord {
	if m != nil {
		return m.Attestations
	}
	return nil
}

type CrystallizedStateHashAnnounce struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrystallizedStateHashAnnounce) Reset()         { *m = CrystallizedStateHashAnnounce{} }
func (m *CrystallizedStateHashAnnounce) String() string { return proto.CompactTextString(m) }
func (*CrystallizedStateHashAnnounce) ProtoMessage()    {}
func (*CrystallizedStateHashAnnounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{5}
}
func (m *CrystallizedStateHashAnnounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrystallizedStateHashAnnounce.Unmarshal(m, b)
}
func (m *CrystallizedStateHashAnnounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrystallizedStateHashAnnounce.Marshal(b, m, deterministic)
}
func (dst *CrystallizedStateHashAnnounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrystallizedStateHashAnnounce.Merge(dst, src)
}
func (m *CrystallizedStateHashAnnounce) XXX_Size() int {
	return xxx_messageInfo_CrystallizedStateHashAnnounce.Size(m)
}
func (m *CrystallizedStateHashAnnounce) XXX_DiscardUnknown() {
	xxx_messageInfo_CrystallizedStateHashAnnounce.DiscardUnknown(m)
}

var xxx_messageInfo_CrystallizedStateHashAnnounce proto.InternalMessageInfo

func (m *CrystallizedStateHashAnnounce) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type CrystallizedStateRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrystallizedStateRequest) Reset()         { *m = CrystallizedStateRequest{} }
func (m *CrystallizedStateRequest) String() string { return proto.CompactTextString(m) }
func (*CrystallizedStateRequest) ProtoMessage()    {}
func (*CrystallizedStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{6}
}
func (m *CrystallizedStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrystallizedStateRequest.Unmarshal(m, b)
}
func (m *CrystallizedStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrystallizedStateRequest.Marshal(b, m, deterministic)
}
func (dst *CrystallizedStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrystallizedStateRequest.Merge(dst, src)
}
func (m *CrystallizedStateRequest) XXX_Size() int {
	return xxx_messageInfo_CrystallizedStateRequest.Size(m)
}
func (m *CrystallizedStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrystallizedStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrystallizedStateRequest proto.InternalMessageInfo

func (m *CrystallizedStateRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type CrystallizedStateResponse struct {
	CrystallizedState    *CrystallizedState `protobuf:"bytes,1,opt,name=crystallized_state,json=crystallizedState,proto3" json:"crystallized_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CrystallizedStateResponse) Reset()         { *m = CrystallizedStateResponse{} }
func (m *CrystallizedStateResponse) String() string { return proto.CompactTextString(m) }
func (*CrystallizedStateResponse) ProtoMessage()    {}
func (*CrystallizedStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{7}
}
func (m *CrystallizedStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrystallizedStateResponse.Unmarshal(m, b)
}
func (m *CrystallizedStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrystallizedStateResponse.Marshal(b, m, deterministic)
}
func (dst *CrystallizedStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrystallizedStateResponse.Merge(dst, src)
}
func (m *CrystallizedStateResponse) XXX_Size() int {
	return xxx_messageInfo_CrystallizedStateResponse.Size(m)
}
func (m *CrystallizedStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrystallizedStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrystallizedStateResponse proto.InternalMessageInfo

func (m *CrystallizedStateResponse) GetCrystallizedState() *CrystallizedState {
	if m != nil {
		return m.CrystallizedState
	}
	return nil
}

type CrystallizedState struct {
	LastStateRecalc            uint64                    `protobuf:"varint,1,opt,name=last_state_recalc,json=lastStateRecalc,proto3" json:"last_state_recalc,omitempty"`
	JustifiedStreak            uint64                    `protobuf:"varint,2,opt,name=justified_streak,json=justifiedStreak,proto3" json:"justified_streak,omitempty"`
	LastJustifiedSlot          uint64                    `protobuf:"varint,3,opt,name=last_justified_slot,json=lastJustifiedSlot,proto3" json:"last_justified_slot,omitempty"`
	LastFinalizedSlot          uint64                    `protobuf:"varint,4,opt,name=last_finalized_slot,json=lastFinalizedSlot,proto3" json:"last_finalized_slot,omitempty"`
	CurrentDynasty             uint64                    `protobuf:"varint,5,opt,name=current_dynasty,json=currentDynasty,proto3" json:"current_dynasty,omitempty"`
	TotalDeposits              uint64                    `protobuf:"varint,6,opt,name=total_deposits,json=totalDeposits,proto3" json:"total_deposits,omitempty"`
	DynastySeed                []byte                    `protobuf:"bytes,7,opt,name=dynasty_seed,json=dynastySeed,proto3" json:"dynasty_seed,omitempty"`
	DynastyStart               uint64                    `protobuf:"varint,8,opt,name=dynasty_start,json=dynastyStart,proto3" json:"dynasty_start,omitempty"`
	CrosslinkRecords           []*CrosslinkRecord        `protobuf:"bytes,9,rep,name=crosslink_records,json=crosslinkRecords,proto3" json:"crosslink_records,omitempty"`
	Validators                 []*ValidatorRecord        `protobuf:"bytes,10,rep,name=validators,proto3" json:"validators,omitempty"`
	ShardAndCommitteesForSlots []*ShardAndCommitteeArray `protobuf:"bytes,11,rep,name=shard_and_committees_for_slots,json=shardAndCommitteesForSlots,proto3" json:"shard_and_committees_for_slots,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                  `json:"-"`
	XXX_unrecognized           []byte                    `json:"-"`
	XXX_sizecache              int32                     `json:"-"`
}

func (m *CrystallizedState) Reset()         { *m = CrystallizedState{} }
func (m *CrystallizedState) String() string { return proto.CompactTextString(m) }
func (*CrystallizedState) ProtoMessage()    {}
func (*CrystallizedState) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{8}
}
func (m *CrystallizedState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrystallizedState.Unmarshal(m, b)
}
func (m *CrystallizedState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrystallizedState.Marshal(b, m, deterministic)
}
func (dst *CrystallizedState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrystallizedState.Merge(dst, src)
}
func (m *CrystallizedState) XXX_Size() int {
	return xxx_messageInfo_CrystallizedState.Size(m)
}
func (m *CrystallizedState) XXX_DiscardUnknown() {
	xxx_messageInfo_CrystallizedState.DiscardUnknown(m)
}

var xxx_messageInfo_CrystallizedState proto.InternalMessageInfo

func (m *CrystallizedState) GetLastStateRecalc() uint64 {
	if m != nil {
		return m.LastStateRecalc
	}
	return 0
}

func (m *CrystallizedState) GetJustifiedStreak() uint64 {
	if m != nil {
		return m.JustifiedStreak
	}
	return 0
}

func (m *CrystallizedState) GetLastJustifiedSlot() uint64 {
	if m != nil {
		return m.LastJustifiedSlot
	}
	return 0
}

func (m *CrystallizedState) GetLastFinalizedSlot() uint64 {
	if m != nil {
		return m.LastFinalizedSlot
	}
	return 0
}

func (m *CrystallizedState) GetCurrentDynasty() uint64 {
	if m != nil {
		return m.CurrentDynasty
	}
	return 0
}

func (m *CrystallizedState) GetTotalDeposits() uint64 {
	if m != nil {
		return m.TotalDeposits
	}
	return 0
}

func (m *CrystallizedState) GetDynastySeed() []byte {
	if m != nil {
		return m.DynastySeed
	}
	return nil
}

func (m *CrystallizedState) GetDynastyStart() uint64 {
	if m != nil {
		return m.DynastyStart
	}
	return 0
}

func (m *CrystallizedState) GetCrosslinkRecords() []*CrosslinkRecord {
	if m != nil {
		return m.CrosslinkRecords
	}
	return nil
}

func (m *CrystallizedState) GetValidators() []*ValidatorRecord {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *CrystallizedState) GetShardAndCommitteesForSlots() []*ShardAndCommitteeArray {
	if m != nil {
		return m.ShardAndCommitteesForSlots
	}
	return nil
}

type ShardAndCommitteeArray struct {
	ArrayShardAndCommittee []*ShardAndCommittee `protobuf:"bytes,1,rep,name=array_shard_and_committee,json=arrayShardAndCommittee,proto3" json:"array_shard_and_committee,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}             `json:"-"`
	XXX_unrecognized       []byte               `json:"-"`
	XXX_sizecache          int32                `json:"-"`
}

func (m *ShardAndCommitteeArray) Reset()         { *m = ShardAndCommitteeArray{} }
func (m *ShardAndCommitteeArray) String() string { return proto.CompactTextString(m) }
func (*ShardAndCommitteeArray) ProtoMessage()    {}
func (*ShardAndCommitteeArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{9}
}
func (m *ShardAndCommitteeArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardAndCommitteeArray.Unmarshal(m, b)
}
func (m *ShardAndCommitteeArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardAndCommitteeArray.Marshal(b, m, deterministic)
}
func (dst *ShardAndCommitteeArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardAndCommitteeArray.Merge(dst, src)
}
func (m *ShardAndCommitteeArray) XXX_Size() int {
	return xxx_messageInfo_ShardAndCommitteeArray.Size(m)
}
func (m *ShardAndCommitteeArray) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardAndCommitteeArray.DiscardUnknown(m)
}

var xxx_messageInfo_ShardAndCommitteeArray proto.InternalMessageInfo

func (m *ShardAndCommitteeArray) GetArrayShardAndCommittee() []*ShardAndCommittee {
	if m != nil {
		return m.ArrayShardAndCommittee
	}
	return nil
}

type ActiveStateHashAnnounce struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActiveStateHashAnnounce) Reset()         { *m = ActiveStateHashAnnounce{} }
func (m *ActiveStateHashAnnounce) String() string { return proto.CompactTextString(m) }
func (*ActiveStateHashAnnounce) ProtoMessage()    {}
func (*ActiveStateHashAnnounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{10}
}
func (m *ActiveStateHashAnnounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveStateHashAnnounce.Unmarshal(m, b)
}
func (m *ActiveStateHashAnnounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveStateHashAnnounce.Marshal(b, m, deterministic)
}
func (dst *ActiveStateHashAnnounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveStateHashAnnounce.Merge(dst, src)
}
func (m *ActiveStateHashAnnounce) XXX_Size() int {
	return xxx_messageInfo_ActiveStateHashAnnounce.Size(m)
}
func (m *ActiveStateHashAnnounce) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveStateHashAnnounce.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveStateHashAnnounce proto.InternalMessageInfo

func (m *ActiveStateHashAnnounce) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ActiveStateRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActiveStateRequest) Reset()         { *m = ActiveStateRequest{} }
func (m *ActiveStateRequest) String() string { return proto.CompactTextString(m) }
func (*ActiveStateRequest) ProtoMessage()    {}
func (*ActiveStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{11}
}
func (m *ActiveStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveStateRequest.Unmarshal(m, b)
}
func (m *ActiveStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveStateRequest.Marshal(b, m, deterministic)
}
func (dst *ActiveStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveStateRequest.Merge(dst, src)
}
func (m *ActiveStateRequest) XXX_Size() int {
	return xxx_messageInfo_ActiveStateRequest.Size(m)
}
func (m *ActiveStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveStateRequest proto.InternalMessageInfo

func (m *ActiveStateRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ShardAndCommittee struct {
	ShardId              uint64   `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Committee            []uint32 `protobuf:"varint,2,rep,packed,name=committee,proto3" json:"committee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardAndCommittee) Reset()         { *m = ShardAndCommittee{} }
func (m *ShardAndCommittee) String() string { return proto.CompactTextString(m) }
func (*ShardAndCommittee) ProtoMessage()    {}
func (*ShardAndCommittee) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{12}
}
func (m *ShardAndCommittee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardAndCommittee.Unmarshal(m, b)
}
func (m *ShardAndCommittee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardAndCommittee.Marshal(b, m, deterministic)
}
func (dst *ShardAndCommittee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardAndCommittee.Merge(dst, src)
}
func (m *ShardAndCommittee) XXX_Size() int {
	return xxx_messageInfo_ShardAndCommittee.Size(m)
}
func (m *ShardAndCommittee) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardAndCommittee.DiscardUnknown(m)
}

var xxx_messageInfo_ShardAndCommittee proto.InternalMessageInfo

func (m *ShardAndCommittee) GetShardId() uint64 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *ShardAndCommittee) GetCommittee() []uint32 {
	if m != nil {
		return m.Committee
	}
	return nil
}

type ActiveStateResponse struct {
	ActiveState          *ActiveState `protobuf:"bytes,1,opt,name=active_state,json=activeState,proto3" json:"active_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ActiveStateResponse) Reset()         { *m = ActiveStateResponse{} }
func (m *ActiveStateResponse) String() string { return proto.CompactTextString(m) }
func (*ActiveStateResponse) ProtoMessage()    {}
func (*ActiveStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{13}
}
func (m *ActiveStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveStateResponse.Unmarshal(m, b)
}
func (m *ActiveStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveStateResponse.Marshal(b, m, deterministic)
}
func (dst *ActiveStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveStateResponse.Merge(dst, src)
}
func (m *ActiveStateResponse) XXX_Size() int {
	return xxx_messageInfo_ActiveStateResponse.Size(m)
}
func (m *ActiveStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveStateResponse proto.InternalMessageInfo

func (m *ActiveStateResponse) GetActiveState() *ActiveState {
	if m != nil {
		return m.ActiveState
	}
	return nil
}

type ActiveState struct {
	PendingAttestations  []*AttestationRecord `protobuf:"bytes,1,rep,name=pending_attestations,json=pendingAttestations,proto3" json:"pending_attestations,omitempty"`
	RecentBlockHashes    [][]byte             `protobuf:"bytes,2,rep,name=recent_block_hashes,json=recentBlockHashes,proto3" json:"recent_block_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ActiveState) Reset()         { *m = ActiveState{} }
func (m *ActiveState) String() string { return proto.CompactTextString(m) }
func (*ActiveState) ProtoMessage()    {}
func (*ActiveState) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{14}
}
func (m *ActiveState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveState.Unmarshal(m, b)
}
func (m *ActiveState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveState.Marshal(b, m, deterministic)
}
func (dst *ActiveState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveState.Merge(dst, src)
}
func (m *ActiveState) XXX_Size() int {
	return xxx_messageInfo_ActiveState.Size(m)
}
func (m *ActiveState) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveState.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveState proto.InternalMessageInfo

func (m *ActiveState) GetPendingAttestations() []*AttestationRecord {
	if m != nil {
		return m.PendingAttestations
	}
	return nil
}

func (m *ActiveState) GetRecentBlockHashes() [][]byte {
	if m != nil {
		return m.RecentBlockHashes
	}
	return nil
}

type ValidatorRecord struct {
	PublicKey            uint64   `protobuf:"varint,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	WithdrawalShard      uint64   `protobuf:"varint,2,opt,name=withdrawal_shard,json=withdrawalShard,proto3" json:"withdrawal_shard,omitempty"`
	WithdrawalAddress    []byte   `protobuf:"bytes,3,opt,name=withdrawal_address,json=withdrawalAddress,proto3" json:"withdrawal_address,omitempty"`
	RandaoCommitment     []byte   `protobuf:"bytes,4,opt,name=randao_commitment,json=randaoCommitment,proto3" json:"randao_commitment,omitempty"`
	Balance              uint64   `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	StartDynasty         uint64   `protobuf:"varint,6,opt,name=start_dynasty,json=startDynasty,proto3" json:"start_dynasty,omitempty"`
	EndDynasty           uint64   `protobuf:"varint,7,opt,name=end_dynasty,json=endDynasty,proto3" json:"end_dynasty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorRecord) Reset()         { *m = ValidatorRecord{} }
func (m *ValidatorRecord) String() string { return proto.CompactTextString(m) }
func (*ValidatorRecord) ProtoMessage()    {}
func (*ValidatorRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{15}
}
func (m *ValidatorRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorRecord.Unmarshal(m, b)
}
func (m *ValidatorRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorRecord.Marshal(b, m, deterministic)
}
func (dst *ValidatorRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorRecord.Merge(dst, src)
}
func (m *ValidatorRecord) XXX_Size() int {
	return xxx_messageInfo_ValidatorRecord.Size(m)
}
func (m *ValidatorRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorRecord proto.InternalMessageInfo

func (m *ValidatorRecord) GetPublicKey() uint64 {
	if m != nil {
		return m.PublicKey
	}
	return 0
}

func (m *ValidatorRecord) GetWithdrawalShard() uint64 {
	if m != nil {
		return m.WithdrawalShard
	}
	return 0
}

func (m *ValidatorRecord) GetWithdrawalAddress() []byte {
	if m != nil {
		return m.WithdrawalAddress
	}
	return nil
}

func (m *ValidatorRecord) GetRandaoCommitment() []byte {
	if m != nil {
		return m.RandaoCommitment
	}
	return nil
}

func (m *ValidatorRecord) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *ValidatorRecord) GetStartDynasty() uint64 {
	if m != nil {
		return m.StartDynasty
	}
	return 0
}

func (m *ValidatorRecord) GetEndDynasty() uint64 {
	if m != nil {
		return m.EndDynasty
	}
	return 0
}

type AttestationRecord struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ShardId              uint64   `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	JustifiedSlot        uint64   `protobuf:"varint,3,opt,name=justified_slot,json=justifiedSlot,proto3" json:"justified_slot,omitempty"`
	JustifiedBlockHash   []byte   `protobuf:"bytes,4,opt,name=justified_block_hash,json=justifiedBlockHash,proto3" json:"justified_block_hash,omitempty"`
	ShardBlockHash       []byte   `protobuf:"bytes,5,opt,name=shard_block_hash,json=shardBlockHash,proto3" json:"shard_block_hash,omitempty"`
	AttesterBitfield     []byte   `protobuf:"bytes,6,opt,name=attester_bitfield,json=attesterBitfield,proto3" json:"attester_bitfield,omitempty"`
	ObliqueParentHashes  [][]byte `protobuf:"bytes,7,rep,name=oblique_parent_hashes,json=obliqueParentHashes,proto3" json:"oblique_parent_hashes,omitempty"`
	AggregateSig         []uint64 `protobuf:"varint,8,rep,packed,name=aggregate_sig,json=aggregateSig,proto3" json:"aggregate_sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttestationRecord) Reset()         { *m = AttestationRecord{} }
func (m *AttestationRecord) String() string { return proto.CompactTextString(m) }
func (*AttestationRecord) ProtoMessage()    {}
func (*AttestationRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{16}
}
func (m *AttestationRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationRecord.Unmarshal(m, b)
}
func (m *AttestationRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationRecord.Marshal(b, m, deterministic)
}
func (dst *AttestationRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationRecord.Merge(dst, src)
}
func (m *AttestationRecord) XXX_Size() int {
	return xxx_messageInfo_AttestationRecord.Size(m)
}
func (m *AttestationRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationRecord proto.InternalMessageInfo

func (m *AttestationRecord) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *AttestationRecord) GetShardId() uint64 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *AttestationRecord) GetJustifiedSlot() uint64 {
	if m != nil {
		return m.JustifiedSlot
	}
	return 0
}

func (m *AttestationRecord) GetJustifiedBlockHash() []byte {
	if m != nil {
		return m.JustifiedBlockHash
	}
	return nil
}

func (m *AttestationRecord) GetShardBlockHash() []byte {
	if m != nil {
		return m.ShardBlockHash
	}
	return nil
}

func (m *AttestationRecord) GetAttesterBitfield() []byte {
	if m != nil {
		return m.AttesterBitfield
	}
	return nil
}

func (m *AttestationRecord) GetObliqueParentHashes() [][]byte {
	if m != nil {
		return m.ObliqueParentHashes
	}
	return nil
}

func (m *AttestationRecord) GetAggregateSig() []uint64 {
	if m != nil {
		return m.AggregateSig
	}
	return nil
}

type CrosslinkRecord struct {
	Dynasty              uint64   `protobuf:"varint,1,opt,name=dynasty,proto3" json:"dynasty,omitempty"`
	Blockhash            []byte   `protobuf:"bytes,2,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	Slot                 uint64   `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrosslinkRecord) Reset()         { *m = CrosslinkRecord{} }
func (m *CrosslinkRecord) String() string { return proto.CompactTextString(m) }
func (*CrosslinkRecord) ProtoMessage()    {}
func (*CrosslinkRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{17}
}
func (m *CrosslinkRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrosslinkRecord.Unmarshal(m, b)
}
func (m *CrosslinkRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrosslinkRecord.Marshal(b, m, deterministic)
}
func (dst *CrosslinkRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrosslinkRecord.Merge(dst, src)
}
func (m *CrosslinkRecord) XXX_Size() int {
	return xxx_messageInfo_CrosslinkRecord.Size(m)
}
func (m *CrosslinkRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CrosslinkRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CrosslinkRecord proto.InternalMessageInfo

func (m *CrosslinkRecord) GetDynasty() uint64 {
	if m != nil {
		return m.Dynasty
	}
	return 0
}

func (m *CrosslinkRecord) GetBlockhash() []byte {
	if m != nil {
		return m.Blockhash
	}
	return nil
}

func (m *CrosslinkRecord) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

type AttestationHashes struct {
	AttestationHash      [][]byte `protobuf:"bytes,1,rep,name=attestation_hash,json=attestationHash,proto3" json:"attestation_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttestationHashes) Reset()         { *m = AttestationHashes{} }
func (m *AttestationHashes) String() string { return proto.CompactTextString(m) }
func (*AttestationHashes) ProtoMessage()    {}
func (*AttestationHashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_5b089ba678a69fa1, []int{18}
}
func (m *AttestationHashes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationHashes.Unmarshal(m, b)
}
func (m *AttestationHashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationHashes.Marshal(b, m, deterministic)
}
func (dst *AttestationHashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationHashes.Merge(dst, src)
}
func (m *AttestationHashes) XXX_Size() int {
	return xxx_messageInfo_AttestationHashes.Size(m)
}
func (m *AttestationHashes) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationHashes.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationHashes proto.InternalMessageInfo

func (m *AttestationHashes) GetAttestationHash() [][]byte {
	if m != nil {
		return m.AttestationHash
	}
	return nil
}

func init() {
	proto.RegisterType((*BeaconBlockHashAnnounce)(nil), "ethereum.beacon.p2p.v1.BeaconBlockHashAnnounce")
	proto.RegisterType((*BeaconBlockRequest)(nil), "ethereum.beacon.p2p.v1.BeaconBlockRequest")
	proto.RegisterType((*BeaconBlockRequestBySlotNumber)(nil), "ethereum.beacon.p2p.v1.BeaconBlockRequestBySlotNumber")
	proto.RegisterType((*BeaconBlockResponse)(nil), "ethereum.beacon.p2p.v1.BeaconBlockResponse")
	proto.RegisterType((*BeaconBlock)(nil), "ethereum.beacon.p2p.v1.BeaconBlock")
	proto.RegisterType((*CrystallizedStateHashAnnounce)(nil), "ethereum.beacon.p2p.v1.CrystallizedStateHashAnnounce")
	proto.RegisterType((*CrystallizedStateRequest)(nil), "ethereum.beacon.p2p.v1.CrystallizedStateRequest")
	proto.RegisterType((*CrystallizedStateResponse)(nil), "ethereum.beacon.p2p.v1.CrystallizedStateResponse")
	proto.RegisterType((*CrystallizedState)(nil), "ethereum.beacon.p2p.v1.CrystallizedState")
	proto.RegisterType((*ShardAndCommitteeArray)(nil), "ethereum.beacon.p2p.v1.ShardAndCommitteeArray")
	proto.RegisterType((*ActiveStateHashAnnounce)(nil), "ethereum.beacon.p2p.v1.ActiveStateHashAnnounce")
	proto.RegisterType((*ActiveStateRequest)(nil), "ethereum.beacon.p2p.v1.ActiveStateRequest")
	proto.RegisterType((*ShardAndCommittee)(nil), "ethereum.beacon.p2p.v1.ShardAndCommittee")
	proto.RegisterType((*ActiveStateResponse)(nil), "ethereum.beacon.p2p.v1.ActiveStateResponse")
	proto.RegisterType((*ActiveState)(nil), "ethereum.beacon.p2p.v1.ActiveState")
	proto.RegisterType((*ValidatorRecord)(nil), "ethereum.beacon.p2p.v1.ValidatorRecord")
	proto.RegisterType((*AttestationRecord)(nil), "ethereum.beacon.p2p.v1.AttestationRecord")
	proto.RegisterType((*CrosslinkRecord)(nil), "ethereum.beacon.p2p.v1.CrosslinkRecord")
	proto.RegisterType((*AttestationHashes)(nil), "ethereum.beacon.p2p.v1.AttestationHashes")
	proto.RegisterEnum("ethereum.beacon.p2p.v1.Topic", Topic_name, Topic_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_5b089ba678a69fa1) }

var fileDescriptor_messages_5b089ba678a69fa1 = []byte{
	// 1308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x26, 0xb6, 0x53, 0x27, 0xc7, 0x4e, 0x62, 0x4f, 0xfa, 0xb3, 0x09, 0xb4, 0x09, 0x5b, 0xaa,
	0xa6, 0xad, 0xea, 0x42, 0x2b, 0x21, 0xb8, 0x41, 0xb2, 0x5d, 0x97, 0x96, 0xa4, 0x4e, 0xd9, 0x75,
	0x0a, 0x45, 0x54, 0xab, 0xf1, 0xee, 0xd8, 0xde, 0x66, 0xbd, 0xe3, 0xce, 0x8c, 0x13, 0x99, 0x0b,
	0xee, 0x78, 0x06, 0x2e, 0x10, 0x4f, 0x84, 0xc4, 0xdb, 0x70, 0x8f, 0x66, 0x76, 0xf6, 0xcf, 0x76,
	0x52, 0xf5, 0x6e, 0xf7, 0x3b, 0xdf, 0x39, 0x73, 0xfe, 0x67, 0x60, 0x73, 0x4c, 0x38, 0xc7, 0x43,
	0xc2, 0x1b, 0x13, 0x46, 0x05, 0x45, 0xd7, 0x89, 0x18, 0x11, 0x46, 0xa6, 0xe3, 0x46, 0x9f, 0x60,
	0x97, 0x86, 0x8d, 0xc9, 0xe3, 0x49, 0xe3, 0xec, 0xab, 0xdd, 0xbd, 0x21, 0xa5, 0xc3, 0x80, 0x3c,
	0x52, 0xac, 0xfe, 0x74, 0xf0, 0x48, 0xf8, 0x63, 0xc2, 0x05, 0x1e, 0x4f, 0x22, 0x45, 0xf3, 0x21,
	0xdc, 0x68, 0x29, 0x8d, 0x56, 0x40, 0xdd, 0xd3, 0xe7, 0x98, 0x8f, 0x9a, 0x61, 0x48, 0xa7, 0xa1,
	0x4b, 0x10, 0x82, 0xd2, 0x08, 0xf3, 0x91, 0xb1, 0xb2, 0xbf, 0x72, 0x50, 0xb5, 0xd4, 0xb7, 0x79,
	0x00, 0x28, 0x43, 0xb7, 0xc8, 0xfb, 0x29, 0xe1, 0x62, 0x29, 0xb3, 0x09, 0xb7, 0x16, 0x99, 0xad,
	0x99, 0x1d, 0x50, 0xd1, 0x9d, 0x8e, 0xfb, 0x84, 0xa1, 0x3d, 0xa8, 0xf0, 0x80, 0x0a, 0x27, 0x54,
	0xbf, 0x4a, 0xb9, 0x64, 0x01, 0x4f, 0x08, 0xe6, 0xdf, 0x2b, 0xb0, 0x9d, 0xb3, 0xc1, 0x27, 0x34,
	0xe4, 0x04, 0x7d, 0x0b, 0xab, 0x7d, 0x09, 0x28, 0x95, 0xca, 0xe3, 0xdb, 0x8d, 0xe5, 0xc1, 0x37,
	0xb2, 0xba, 0x91, 0x06, 0x3a, 0x84, 0x0a, 0x16, 0x42, 0x66, 0x40, 0xf8, 0x34, 0x34, 0x0a, 0xca,
	0xc0, 0xbd, 0x8b, 0x0c, 0x34, 0x53, 0xaa, 0x45, 0x5c, 0xca, 0x3c, 0x2b, 0xab, 0x6d, 0xfe, 0x51,
	0x84, 0x4a, 0xe6, 0x0c, 0x19, 0xd0, 0x04, 0x33, 0x12, 0x0a, 0x27, 0x93, 0x0d, 0x88, 0x20, 0x99,
	0xd9, 0xf9, 0x88, 0x0b, 0xf3, 0x11, 0xa3, 0xdb, 0xb0, 0xc1, 0x70, 0xe8, 0x61, 0xea, 0x30, 0x72,
	0x46, 0x70, 0x60, 0x14, 0x95, 0x8d, 0x6a, 0x04, 0x5a, 0x0a, 0x43, 0x26, 0x6c, 0x4c, 0xe8, 0xb9,
	0xe3, 0x8e, 0xb0, 0x1f, 0x3a, 0x8c, 0x0c, 0x8c, 0x92, 0x22, 0x55, 0x26, 0xf4, 0xbc, 0x2d, 0x31,
	0x8b, 0x0c, 0xd0, 0x7d, 0xa8, 0x63, 0x57, 0xf8, 0x67, 0xc4, 0x91, 0xce, 0x92, 0xc8, 0xa1, 0x55,
	0xc5, 0xdb, 0x8a, 0x04, 0xb6, 0xc4, 0x95, 0x57, 0x5f, 0xc3, 0x0d, 0x97, 0xcd, 0xb8, 0xc0, 0x41,
	0xe0, 0xff, 0x46, 0xbc, 0xac, 0xc6, 0x15, 0xa5, 0x71, 0x2d, 0x2b, 0x4e, 0xf5, 0xbe, 0x81, 0xf5,
	0xa4, 0x9b, 0x8c, 0xb2, 0xca, 0xe4, 0x6e, 0x23, 0xea, 0xb7, 0x46, 0xdc, 0x6f, 0x8d, 0x5e, 0xcc,
	0xb0, 0x52, 0x32, 0x7a, 0x09, 0xd5, 0x4c, 0x1e, 0xb9, 0xb1, 0xb6, 0x5f, 0xfc, 0xb8, 0x32, 0xe4,
	0xd4, 0xcd, 0x27, 0x70, 0xb3, 0xbd, 0xcc, 0xc3, 0x4b, 0x3b, 0xb9, 0x01, 0xc6, 0x82, 0xd2, 0x65,
	0xfd, 0x3c, 0x85, 0x9d, 0x25, 0x7c, 0xdd, 0x91, 0x3f, 0x03, 0x5a, 0x4c, 0xa1, 0x6e, 0xcf, 0x0b,
	0xc3, 0x5a, 0x34, 0x57, 0x5f, 0x48, 0xb4, 0xf9, 0x5f, 0x09, 0xea, 0x0b, 0x44, 0x59, 0xde, 0x00,
	0x73, 0xa1, 0x4b, 0xc5, 0x88, 0x8b, 0x03, 0x57, 0x0f, 0xd0, 0x96, 0x14, 0x68, 0xef, 0x24, 0x8c,
	0xee, 0x41, 0xed, 0xdd, 0x94, 0x0b, 0x7f, 0xe0, 0x2b, 0xc7, 0x18, 0xc1, 0xa7, 0xba, 0xf3, 0xb6,
	0x12, 0xdc, 0x56, 0x30, 0x6a, 0xc0, 0xb6, 0x32, 0x9b, 0xe1, 0x07, 0x54, 0xa8, 0x26, 0x2c, 0x59,
	0xea, 0xc4, 0x1f, 0x12, 0x8d, 0x80, 0x8a, 0x84, 0x3f, 0xf0, 0x43, 0xac, 0x03, 0x97, 0xfc, 0x52,
	0xca, 0x7f, 0x16, 0x4b, 0x14, 0xff, 0x2e, 0x6c, 0xb9, 0x53, 0xa6, 0x26, 0xc4, 0x9b, 0x85, 0x98,
	0x8b, 0x99, 0xea, 0xc9, 0x92, 0xb5, 0xa9, 0xe1, 0xa7, 0x11, 0x8a, 0xee, 0xc0, 0xa6, 0xa0, 0x02,
	0x07, 0x8e, 0x47, 0x26, 0x94, 0xfb, 0x82, 0xab, 0x4e, 0x2c, 0x59, 0x1b, 0x0a, 0x7d, 0xaa, 0x41,
	0xf4, 0x39, 0x54, 0xb5, 0x1d, 0x87, 0x13, 0xe2, 0xa9, 0x26, 0xac, 0x5a, 0x15, 0x8d, 0xd9, 0x84,
	0x78, 0x72, 0xa2, 0x12, 0x8a, 0xc0, 0x4c, 0x18, 0x6b, 0xca, 0x50, 0xac, 0x67, 0x4b, 0x0c, 0xf5,
	0xa0, 0xee, 0x32, 0xca, 0x79, 0xe0, 0x87, 0xa7, 0x32, 0x9b, 0x94, 0x79, 0xdc, 0x58, 0x57, 0x4d,
	0x79, 0xf7, 0xe2, 0xea, 0x69, 0x05, 0xdd, 0x92, 0x35, 0x37, 0x0f, 0x70, 0xf4, 0x3d, 0xc0, 0x19,
	0x0e, 0x7c, 0x0f, 0x0b, 0xca, 0xb8, 0x01, 0x97, 0x9b, 0x7b, 0x1d, 0x33, 0xb5, 0xb9, 0x8c, 0x2a,
	0x62, 0x70, 0x8b, 0x8f, 0x30, 0xf3, 0x1c, 0x1c, 0x7a, 0x8e, 0x4b, 0xc7, 0x63, 0x5f, 0x08, 0x42,
	0xb8, 0x33, 0xa0, 0x4c, 0x25, 0x9c, 0x1b, 0x15, 0x65, 0xbc, 0x71, 0x91, 0x71, 0x5b, 0x6a, 0x37,
	0x43, 0xaf, 0x1d, 0xeb, 0x36, 0x19, 0xc3, 0x33, 0x6b, 0x97, 0xcf, 0xe3, 0xfc, 0x19, 0x65, 0xb2,
	0x52, 0xdc, 0xfc, 0x1d, 0xae, 0x2f, 0xd7, 0x42, 0x1e, 0xec, 0x60, 0xf9, 0xe1, 0x2c, 0xf1, 0xc9,
	0x58, 0xb9, 0x7c, 0x92, 0x17, 0x4c, 0x5a, 0xd7, 0x95, 0xad, 0x05, 0x5c, 0xde, 0x4b, 0xcd, 0xfc,
	0x9e, 0xfa, 0xd0, 0xbd, 0x94, 0xa1, 0x5f, 0x36, 0xc7, 0x47, 0x50, 0x5f, 0x38, 0x0d, 0xed, 0xc0,
	0x5a, 0x14, 0x8d, 0xef, 0xe9, 0x31, 0x2a, 0xab, 0xff, 0x17, 0x1e, 0xfa, 0x0c, 0xd6, 0xd3, 0xf0,
	0x0a, 0xfb, 0xc5, 0x83, 0x0d, 0x2b, 0x05, 0xcc, 0xb7, 0xb0, 0x9d, 0x3b, 0x57, 0xef, 0x83, 0x67,
	0x50, 0xcd, 0xae, 0xdf, 0x0f, 0x5d, 0x54, 0x59, 0x13, 0x95, 0xcc, 0x7a, 0x36, 0xff, 0x5a, 0x81,
	0x4a, 0x46, 0x88, 0x7e, 0x85, 0xab, 0x13, 0x12, 0x7a, 0x7e, 0x38, 0x74, 0x72, 0x0b, 0x74, 0xe5,
	0x63, 0x17, 0xe8, 0xb6, 0x36, 0x93, 0x91, 0x70, 0x39, 0xce, 0x8c, 0xb8, 0x72, 0x3a, 0xd5, 0x65,
	0xa9, 0xae, 0x00, 0xc2, 0x55, 0xd0, 0x55, 0xab, 0x1e, 0x89, 0x92, 0x67, 0x02, 0xe1, 0xe6, 0x9f,
	0x05, 0xd8, 0x9a, 0xeb, 0x5b, 0x74, 0x13, 0x60, 0x32, 0xed, 0x07, 0xbe, 0xeb, 0x9c, 0x92, 0x99,
	0xce, 0xe5, 0x7a, 0x84, 0x1c, 0x92, 0x99, 0x5c, 0x46, 0xe7, 0xbe, 0x18, 0x79, 0x0c, 0x9f, 0xe3,
	0x20, 0xea, 0xa0, 0x78, 0x19, 0xa5, 0xb8, 0xaa, 0x0f, 0x7a, 0x08, 0x28, 0x43, 0xc5, 0x9e, 0xc7,
	0x08, 0xe7, 0xfa, 0x42, 0xac, 0xa7, 0x92, 0x66, 0x24, 0x40, 0x0f, 0xa0, 0xae, 0xaf, 0xce, 0xa8,
	0x3a, 0x63, 0x12, 0x0a, 0x7d, 0x33, 0xd6, 0x22, 0x41, 0x3b, 0xc1, 0x91, 0x01, 0xe5, 0x3e, 0x0e,
	0x70, 0xe8, 0x12, 0xbd, 0x80, 0xe2, 0x5f, 0xb9, 0x2f, 0xd4, 0x9e, 0x48, 0x16, 0x54, 0xb4, 0x78,
	0xaa, 0x0a, 0x8c, 0xd7, 0xd3, 0x1e, 0x54, 0x48, 0xe8, 0x25, 0x94, 0x72, 0x74, 0x8f, 0x93, 0xd0,
	0xd3, 0x04, 0xf3, 0x9f, 0x02, 0xd4, 0x17, 0x92, 0x2e, 0xdb, 0x51, 0xed, 0xc7, 0x28, 0x2b, 0xea,
	0x3b, 0xd7, 0x79, 0x85, 0x7c, 0xe7, 0xdd, 0x81, 0xcd, 0xa5, 0x8b, 0x78, 0xe3, 0x5d, 0x6e, 0x09,
	0x7f, 0x09, 0x57, 0x53, 0x5a, 0x5a, 0x38, 0x1d, 0x3b, 0x4a, 0x64, 0x49, 0xe5, 0xd0, 0x01, 0xd4,
	0xa2, 0x33, 0x33, 0xec, 0xe8, 0x6d, 0xb0, 0xa9, 0xf0, 0x94, 0xf9, 0x00, 0xea, 0x51, 0x9f, 0x11,
	0xe6, 0xf4, 0x7d, 0x31, 0xf0, 0x49, 0xe0, 0xe9, 0x47, 0x41, 0x2d, 0x16, 0xb4, 0x34, 0x8e, 0x1e,
	0xc3, 0x35, 0xda, 0x0f, 0xfc, 0xf7, 0x53, 0xe2, 0x64, 0x9e, 0x41, 0x84, 0x1b, 0x65, 0xd5, 0x40,
	0xdb, 0x5a, 0xf8, 0x2a, 0x79, 0x0f, 0x11, 0x2e, 0xd3, 0x8d, 0x87, 0x43, 0x46, 0x86, 0xf2, 0x1e,
	0xe3, 0xfe, 0x50, 0x3d, 0x05, 0x4a, 0x56, 0x35, 0x01, 0x6d, 0x7f, 0x68, 0xbe, 0x85, 0xad, 0xb9,
	0x6d, 0x2b, 0x0b, 0x18, 0x67, 0x5f, 0xcf, 0xab, 0xfe, 0x95, 0xf3, 0xaa, 0xc2, 0x52, 0x51, 0x15,
	0x94, 0xab, 0x29, 0x90, 0x94, 0xa0, 0x98, 0x96, 0xc0, 0xfc, 0x2e, 0x57, 0x2b, 0xed, 0xd8, 0x3d,
	0xa8, 0x65, 0x26, 0x2c, 0x7e, 0xd0, 0x15, 0xd5, 0xfb, 0x29, 0x4f, 0xbe, 0xff, 0x6f, 0x01, 0x56,
	0x7b, 0x74, 0xe2, 0xbb, 0xa8, 0x02, 0xe5, 0x93, 0xee, 0x61, 0xf7, 0xf8, 0xa7, 0x6e, 0xed, 0x13,
	0x74, 0x0b, 0x76, 0x5b, 0x9d, 0x66, 0xfb, 0xb8, 0xeb, 0xb4, 0x8e, 0x8e, 0xdb, 0x87, 0xce, 0xf3,
	0xa6, 0xfd, 0xdc, 0x69, 0x76, 0xbb, 0xc7, 0x27, 0xdd, 0x76, 0xa7, 0xb6, 0x82, 0x0c, 0xb8, 0x9a,
	0x93, 0x5b, 0x9d, 0x1f, 0x4f, 0x3a, 0x76, 0xaf, 0x56, 0x40, 0x77, 0xe1, 0xf6, 0x32, 0x89, 0xd3,
	0x7a, 0xe3, 0xd8, 0x47, 0xc7, 0x3d, 0xa7, 0x7b, 0xf2, 0xb2, 0xd5, 0xb1, 0x6a, 0x45, 0xb4, 0x03,
	0xd7, 0xe6, 0x88, 0xf6, 0xab, 0xe3, 0xae, 0xdd, 0xa9, 0x95, 0xd0, 0x17, 0xb0, 0xdf, 0xb6, 0xde,
	0xd8, 0xbd, 0xe6, 0xd1, 0xd1, 0x8b, 0x5f, 0x3a, 0x4f, 0x1d, 0xbb, 0xd7, 0xec, 0x75, 0xe6, 0x7c,
	0x58, 0x95, 0x3e, 0x2e, 0x61, 0xc5, 0x9e, 0x5c, 0x41, 0x7b, 0xf0, 0xe9, 0x52, 0xb9, 0x3e, 0xa6,
	0x2c, 0x0d, 0x34, 0xdb, 0xbd, 0x17, 0xaf, 0x3b, 0x4b, 0x0f, 0x58, 0x93, 0x41, 0xe6, 0xe4, 0xb1,
	0xe9, 0x75, 0xe9, 0xfb, 0x9c, 0x44, 0x1b, 0x85, 0xfe, 0x15, 0xf5, 0x7a, 0x7c, 0xf2, 0x7f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xad, 0x61, 0xe0, 0xb8, 0xe5, 0x0c, 0x00, 0x00,
}
