// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/beacon/p2p/v1/messages.proto

package ethereum_beacon_p2p_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BeaconBlockHashAnnounce struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeaconBlockHashAnnounce) Reset()         { *m = BeaconBlockHashAnnounce{} }
func (m *BeaconBlockHashAnnounce) String() string { return proto.CompactTextString(m) }
func (*BeaconBlockHashAnnounce) ProtoMessage()    {}
func (*BeaconBlockHashAnnounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{0}
}
func (m *BeaconBlockHashAnnounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlockHashAnnounce.Unmarshal(m, b)
}
func (m *BeaconBlockHashAnnounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlockHashAnnounce.Marshal(b, m, deterministic)
}
func (dst *BeaconBlockHashAnnounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlockHashAnnounce.Merge(dst, src)
}
func (m *BeaconBlockHashAnnounce) XXX_Size() int {
	return xxx_messageInfo_BeaconBlockHashAnnounce.Size(m)
}
func (m *BeaconBlockHashAnnounce) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlockHashAnnounce.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlockHashAnnounce proto.InternalMessageInfo

func (m *BeaconBlockHashAnnounce) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type BeaconBlockRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeaconBlockRequest) Reset()         { *m = BeaconBlockRequest{} }
func (m *BeaconBlockRequest) String() string { return proto.CompactTextString(m) }
func (*BeaconBlockRequest) ProtoMessage()    {}
func (*BeaconBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{1}
}
func (m *BeaconBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlockRequest.Unmarshal(m, b)
}
func (m *BeaconBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlockRequest.Marshal(b, m, deterministic)
}
func (dst *BeaconBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlockRequest.Merge(dst, src)
}
func (m *BeaconBlockRequest) XXX_Size() int {
	return xxx_messageInfo_BeaconBlockRequest.Size(m)
}
func (m *BeaconBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlockRequest proto.InternalMessageInfo

func (m *BeaconBlockRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type BeaconBlockRequestBySlotNumber struct {
	SlotNumber           uint64   `protobuf:"varint,1,opt,name=slot_number,json=slotNumber,proto3" json:"slot_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeaconBlockRequestBySlotNumber) Reset()         { *m = BeaconBlockRequestBySlotNumber{} }
func (m *BeaconBlockRequestBySlotNumber) String() string { return proto.CompactTextString(m) }
func (*BeaconBlockRequestBySlotNumber) ProtoMessage()    {}
func (*BeaconBlockRequestBySlotNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{2}
}
func (m *BeaconBlockRequestBySlotNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlockRequestBySlotNumber.Unmarshal(m, b)
}
func (m *BeaconBlockRequestBySlotNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlockRequestBySlotNumber.Marshal(b, m, deterministic)
}
func (dst *BeaconBlockRequestBySlotNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlockRequestBySlotNumber.Merge(dst, src)
}
func (m *BeaconBlockRequestBySlotNumber) XXX_Size() int {
	return xxx_messageInfo_BeaconBlockRequestBySlotNumber.Size(m)
}
func (m *BeaconBlockRequestBySlotNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlockRequestBySlotNumber.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlockRequestBySlotNumber proto.InternalMessageInfo

func (m *BeaconBlockRequestBySlotNumber) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

type BeaconBlockResponse struct {
	Block                *BeaconBlock `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BeaconBlockResponse) Reset()         { *m = BeaconBlockResponse{} }
func (m *BeaconBlockResponse) String() string { return proto.CompactTextString(m) }
func (*BeaconBlockResponse) ProtoMessage()    {}
func (*BeaconBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{3}
}
func (m *BeaconBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlockResponse.Unmarshal(m, b)
}
func (m *BeaconBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlockResponse.Marshal(b, m, deterministic)
}
func (dst *BeaconBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlockResponse.Merge(dst, src)
}
func (m *BeaconBlockResponse) XXX_Size() int {
	return xxx_messageInfo_BeaconBlockResponse.Size(m)
}
func (m *BeaconBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlockResponse proto.InternalMessageInfo

func (m *BeaconBlockResponse) GetBlock() *BeaconBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

type BeaconBlock struct {
	ParentHash            []byte               `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	SlotNumber            uint64               `protobuf:"varint,2,opt,name=slot_number,json=slotNumber,proto3" json:"slot_number,omitempty"`
	RandaoReveal          []byte               `protobuf:"bytes,3,opt,name=randao_reveal,json=randaoReveal,proto3" json:"randao_reveal,omitempty"`
	PowChainRef           []byte               `protobuf:"bytes,4,opt,name=pow_chain_ref,json=powChainRef,proto3" json:"pow_chain_ref,omitempty"`
	ActiveStateHash       []byte               `protobuf:"bytes,5,opt,name=active_state_hash,json=activeStateHash,proto3" json:"active_state_hash,omitempty"`
	CrystallizedStateHash []byte               `protobuf:"bytes,6,opt,name=crystallized_state_hash,json=crystallizedStateHash,proto3" json:"crystallized_state_hash,omitempty"`
	Timestamp             *timestamp.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Attestations          []*AttestationRecord `protobuf:"bytes,8,rep,name=attestations,proto3" json:"attestations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *BeaconBlock) Reset()         { *m = BeaconBlock{} }
func (m *BeaconBlock) String() string { return proto.CompactTextString(m) }
func (*BeaconBlock) ProtoMessage()    {}
func (*BeaconBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{4}
}
func (m *BeaconBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlock.Unmarshal(m, b)
}
func (m *BeaconBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlock.Marshal(b, m, deterministic)
}
func (dst *BeaconBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlock.Merge(dst, src)
}
func (m *BeaconBlock) XXX_Size() int {
	return xxx_messageInfo_BeaconBlock.Size(m)
}
func (m *BeaconBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlock.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlock proto.InternalMessageInfo

func (m *BeaconBlock) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BeaconBlock) GetSlotNumber() uint64 {
	if m != nil {
		return m.SlotNumber
	}
	return 0
}

func (m *BeaconBlock) GetRandaoReveal() []byte {
	if m != nil {
		return m.RandaoReveal
	}
	return nil
}

func (m *BeaconBlock) GetPowChainRef() []byte {
	if m != nil {
		return m.PowChainRef
	}
	return nil
}

func (m *BeaconBlock) GetActiveStateHash() []byte {
	if m != nil {
		return m.ActiveStateHash
	}
	return nil
}

func (m *BeaconBlock) GetCrystallizedStateHash() []byte {
	if m != nil {
		return m.CrystallizedStateHash
	}
	return nil
}

func (m *BeaconBlock) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *BeaconBlock) GetAttestations() []*AttestationRecord {
	if m != nil {
		return m.Attestations
	}
	return nil
}

type CrystallizedStateHashAnnounce struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrystallizedStateHashAnnounce) Reset()         { *m = CrystallizedStateHashAnnounce{} }
func (m *CrystallizedStateHashAnnounce) String() string { return proto.CompactTextString(m) }
func (*CrystallizedStateHashAnnounce) ProtoMessage()    {}
func (*CrystallizedStateHashAnnounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{5}
}
func (m *CrystallizedStateHashAnnounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrystallizedStateHashAnnounce.Unmarshal(m, b)
}
func (m *CrystallizedStateHashAnnounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrystallizedStateHashAnnounce.Marshal(b, m, deterministic)
}
func (dst *CrystallizedStateHashAnnounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrystallizedStateHashAnnounce.Merge(dst, src)
}
func (m *CrystallizedStateHashAnnounce) XXX_Size() int {
	return xxx_messageInfo_CrystallizedStateHashAnnounce.Size(m)
}
func (m *CrystallizedStateHashAnnounce) XXX_DiscardUnknown() {
	xxx_messageInfo_CrystallizedStateHashAnnounce.DiscardUnknown(m)
}

var xxx_messageInfo_CrystallizedStateHashAnnounce proto.InternalMessageInfo

func (m *CrystallizedStateHashAnnounce) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type CrystallizedStateRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrystallizedStateRequest) Reset()         { *m = CrystallizedStateRequest{} }
func (m *CrystallizedStateRequest) String() string { return proto.CompactTextString(m) }
func (*CrystallizedStateRequest) ProtoMessage()    {}
func (*CrystallizedStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{6}
}
func (m *CrystallizedStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrystallizedStateRequest.Unmarshal(m, b)
}
func (m *CrystallizedStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrystallizedStateRequest.Marshal(b, m, deterministic)
}
func (dst *CrystallizedStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrystallizedStateRequest.Merge(dst, src)
}
func (m *CrystallizedStateRequest) XXX_Size() int {
	return xxx_messageInfo_CrystallizedStateRequest.Size(m)
}
func (m *CrystallizedStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrystallizedStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrystallizedStateRequest proto.InternalMessageInfo

func (m *CrystallizedStateRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type CrystallizedStateResponse struct {
	CrystallizedState    *CrystallizedState `protobuf:"bytes,1,opt,name=crystallized_state,json=crystallizedState,proto3" json:"crystallized_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CrystallizedStateResponse) Reset()         { *m = CrystallizedStateResponse{} }
func (m *CrystallizedStateResponse) String() string { return proto.CompactTextString(m) }
func (*CrystallizedStateResponse) ProtoMessage()    {}
func (*CrystallizedStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{7}
}
func (m *CrystallizedStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrystallizedStateResponse.Unmarshal(m, b)
}
func (m *CrystallizedStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrystallizedStateResponse.Marshal(b, m, deterministic)
}
func (dst *CrystallizedStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrystallizedStateResponse.Merge(dst, src)
}
func (m *CrystallizedStateResponse) XXX_Size() int {
	return xxx_messageInfo_CrystallizedStateResponse.Size(m)
}
func (m *CrystallizedStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrystallizedStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrystallizedStateResponse proto.InternalMessageInfo

func (m *CrystallizedStateResponse) GetCrystallizedState() *CrystallizedState {
	if m != nil {
		return m.CrystallizedState
	}
	return nil
}

type CrystallizedState struct {
	LastStateRecalc        uint64                    `protobuf:"varint,1,opt,name=last_state_recalc,json=lastStateRecalc,proto3" json:"last_state_recalc,omitempty"`
	JustifiedStreak        uint64                    `protobuf:"varint,2,opt,name=justified_streak,json=justifiedStreak,proto3" json:"justified_streak,omitempty"`
	LastJustifiedSlot      uint64                    `protobuf:"varint,3,opt,name=last_justified_slot,json=lastJustifiedSlot,proto3" json:"last_justified_slot,omitempty"`
	LastFinalizedSlot      uint64                    `protobuf:"varint,4,opt,name=last_finalized_slot,json=lastFinalizedSlot,proto3" json:"last_finalized_slot,omitempty"`
	CurrentDynasty         uint64                    `protobuf:"varint,5,opt,name=current_dynasty,json=currentDynasty,proto3" json:"current_dynasty,omitempty"`
	CrosslinkingStartShard uint64                    `protobuf:"varint,6,opt,name=crosslinking_start_shard,json=crosslinkingStartShard,proto3" json:"crosslinking_start_shard,omitempty"`
	TotalDeposits          uint64                    `protobuf:"varint,7,opt,name=total_deposits,json=totalDeposits,proto3" json:"total_deposits,omitempty"`
	DynastySeed            []byte                    `protobuf:"bytes,8,opt,name=dynasty_seed,json=dynastySeed,proto3" json:"dynasty_seed,omitempty"`
	DynastySeedLastReset   uint64                    `protobuf:"varint,9,opt,name=dynasty_seed_last_reset,json=dynastySeedLastReset,proto3" json:"dynasty_seed_last_reset,omitempty"`
	CrosslinkRecords       []*CrosslinkRecord        `protobuf:"bytes,10,rep,name=crosslink_records,json=crosslinkRecords,proto3" json:"crosslink_records,omitempty"`
	Validators             []*ValidatorRecord        `protobuf:"bytes,11,rep,name=validators,proto3" json:"validators,omitempty"`
	IndicesForHeights      []*ShardAndCommitteeArray `protobuf:"bytes,12,rep,name=indices_for_heights,json=indicesForHeights,proto3" json:"indices_for_heights,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                  `json:"-"`
	XXX_unrecognized       []byte                    `json:"-"`
	XXX_sizecache          int32                     `json:"-"`
}

func (m *CrystallizedState) Reset()         { *m = CrystallizedState{} }
func (m *CrystallizedState) String() string { return proto.CompactTextString(m) }
func (*CrystallizedState) ProtoMessage()    {}
func (*CrystallizedState) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{8}
}
func (m *CrystallizedState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrystallizedState.Unmarshal(m, b)
}
func (m *CrystallizedState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrystallizedState.Marshal(b, m, deterministic)
}
func (dst *CrystallizedState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrystallizedState.Merge(dst, src)
}
func (m *CrystallizedState) XXX_Size() int {
	return xxx_messageInfo_CrystallizedState.Size(m)
}
func (m *CrystallizedState) XXX_DiscardUnknown() {
	xxx_messageInfo_CrystallizedState.DiscardUnknown(m)
}

var xxx_messageInfo_CrystallizedState proto.InternalMessageInfo

func (m *CrystallizedState) GetLastStateRecalc() uint64 {
	if m != nil {
		return m.LastStateRecalc
	}
	return 0
}

func (m *CrystallizedState) GetJustifiedStreak() uint64 {
	if m != nil {
		return m.JustifiedStreak
	}
	return 0
}

func (m *CrystallizedState) GetLastJustifiedSlot() uint64 {
	if m != nil {
		return m.LastJustifiedSlot
	}
	return 0
}

func (m *CrystallizedState) GetLastFinalizedSlot() uint64 {
	if m != nil {
		return m.LastFinalizedSlot
	}
	return 0
}

func (m *CrystallizedState) GetCurrentDynasty() uint64 {
	if m != nil {
		return m.CurrentDynasty
	}
	return 0
}

func (m *CrystallizedState) GetCrosslinkingStartShard() uint64 {
	if m != nil {
		return m.CrosslinkingStartShard
	}
	return 0
}

func (m *CrystallizedState) GetTotalDeposits() uint64 {
	if m != nil {
		return m.TotalDeposits
	}
	return 0
}

func (m *CrystallizedState) GetDynastySeed() []byte {
	if m != nil {
		return m.DynastySeed
	}
	return nil
}

func (m *CrystallizedState) GetDynastySeedLastReset() uint64 {
	if m != nil {
		return m.DynastySeedLastReset
	}
	return 0
}

func (m *CrystallizedState) GetCrosslinkRecords() []*CrosslinkRecord {
	if m != nil {
		return m.CrosslinkRecords
	}
	return nil
}

func (m *CrystallizedState) GetValidators() []*ValidatorRecord {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *CrystallizedState) GetIndicesForHeights() []*ShardAndCommitteeArray {
	if m != nil {
		return m.IndicesForHeights
	}
	return nil
}

type ShardAndCommitteeArray struct {
	ArrayShardAndCommittee []*ShardAndCommittee `protobuf:"bytes,1,rep,name=array_shard_and_committee,json=arrayShardAndCommittee,proto3" json:"array_shard_and_committee,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}             `json:"-"`
	XXX_unrecognized       []byte               `json:"-"`
	XXX_sizecache          int32                `json:"-"`
}

func (m *ShardAndCommitteeArray) Reset()         { *m = ShardAndCommitteeArray{} }
func (m *ShardAndCommitteeArray) String() string { return proto.CompactTextString(m) }
func (*ShardAndCommitteeArray) ProtoMessage()    {}
func (*ShardAndCommitteeArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{9}
}
func (m *ShardAndCommitteeArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardAndCommitteeArray.Unmarshal(m, b)
}
func (m *ShardAndCommitteeArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardAndCommitteeArray.Marshal(b, m, deterministic)
}
func (dst *ShardAndCommitteeArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardAndCommitteeArray.Merge(dst, src)
}
func (m *ShardAndCommitteeArray) XXX_Size() int {
	return xxx_messageInfo_ShardAndCommitteeArray.Size(m)
}
func (m *ShardAndCommitteeArray) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardAndCommitteeArray.DiscardUnknown(m)
}

var xxx_messageInfo_ShardAndCommitteeArray proto.InternalMessageInfo

func (m *ShardAndCommitteeArray) GetArrayShardAndCommittee() []*ShardAndCommittee {
	if m != nil {
		return m.ArrayShardAndCommittee
	}
	return nil
}

type ActiveStateHashAnnounce struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActiveStateHashAnnounce) Reset()         { *m = ActiveStateHashAnnounce{} }
func (m *ActiveStateHashAnnounce) String() string { return proto.CompactTextString(m) }
func (*ActiveStateHashAnnounce) ProtoMessage()    {}
func (*ActiveStateHashAnnounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{10}
}
func (m *ActiveStateHashAnnounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveStateHashAnnounce.Unmarshal(m, b)
}
func (m *ActiveStateHashAnnounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveStateHashAnnounce.Marshal(b, m, deterministic)
}
func (dst *ActiveStateHashAnnounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveStateHashAnnounce.Merge(dst, src)
}
func (m *ActiveStateHashAnnounce) XXX_Size() int {
	return xxx_messageInfo_ActiveStateHashAnnounce.Size(m)
}
func (m *ActiveStateHashAnnounce) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveStateHashAnnounce.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveStateHashAnnounce proto.InternalMessageInfo

func (m *ActiveStateHashAnnounce) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ActiveStateRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActiveStateRequest) Reset()         { *m = ActiveStateRequest{} }
func (m *ActiveStateRequest) String() string { return proto.CompactTextString(m) }
func (*ActiveStateRequest) ProtoMessage()    {}
func (*ActiveStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{11}
}
func (m *ActiveStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveStateRequest.Unmarshal(m, b)
}
func (m *ActiveStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveStateRequest.Marshal(b, m, deterministic)
}
func (dst *ActiveStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveStateRequest.Merge(dst, src)
}
func (m *ActiveStateRequest) XXX_Size() int {
	return xxx_messageInfo_ActiveStateRequest.Size(m)
}
func (m *ActiveStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveStateRequest proto.InternalMessageInfo

func (m *ActiveStateRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ShardAndCommittee struct {
	ShardId              uint64   `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Committee            []uint32 `protobuf:"varint,2,rep,packed,name=committee,proto3" json:"committee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardAndCommittee) Reset()         { *m = ShardAndCommittee{} }
func (m *ShardAndCommittee) String() string { return proto.CompactTextString(m) }
func (*ShardAndCommittee) ProtoMessage()    {}
func (*ShardAndCommittee) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{12}
}
func (m *ShardAndCommittee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardAndCommittee.Unmarshal(m, b)
}
func (m *ShardAndCommittee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardAndCommittee.Marshal(b, m, deterministic)
}
func (dst *ShardAndCommittee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardAndCommittee.Merge(dst, src)
}
func (m *ShardAndCommittee) XXX_Size() int {
	return xxx_messageInfo_ShardAndCommittee.Size(m)
}
func (m *ShardAndCommittee) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardAndCommittee.DiscardUnknown(m)
}

var xxx_messageInfo_ShardAndCommittee proto.InternalMessageInfo

func (m *ShardAndCommittee) GetShardId() uint64 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *ShardAndCommittee) GetCommittee() []uint32 {
	if m != nil {
		return m.Committee
	}
	return nil
}

type ActiveStateResponse struct {
	ActiveState          *ActiveState `protobuf:"bytes,1,opt,name=active_state,json=activeState,proto3" json:"active_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ActiveStateResponse) Reset()         { *m = ActiveStateResponse{} }
func (m *ActiveStateResponse) String() string { return proto.CompactTextString(m) }
func (*ActiveStateResponse) ProtoMessage()    {}
func (*ActiveStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{13}
}
func (m *ActiveStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveStateResponse.Unmarshal(m, b)
}
func (m *ActiveStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveStateResponse.Marshal(b, m, deterministic)
}
func (dst *ActiveStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveStateResponse.Merge(dst, src)
}
func (m *ActiveStateResponse) XXX_Size() int {
	return xxx_messageInfo_ActiveStateResponse.Size(m)
}
func (m *ActiveStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveStateResponse proto.InternalMessageInfo

func (m *ActiveStateResponse) GetActiveState() *ActiveState {
	if m != nil {
		return m.ActiveState
	}
	return nil
}

type ActiveState struct {
	PendingAttestations  []*AttestationRecord `protobuf:"bytes,1,rep,name=pending_attestations,json=pendingAttestations,proto3" json:"pending_attestations,omitempty"`
	RecentBlockHashes    [][]byte             `protobuf:"bytes,2,rep,name=recent_block_hashes,json=recentBlockHashes,proto3" json:"recent_block_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ActiveState) Reset()         { *m = ActiveState{} }
func (m *ActiveState) String() string { return proto.CompactTextString(m) }
func (*ActiveState) ProtoMessage()    {}
func (*ActiveState) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{14}
}
func (m *ActiveState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveState.Unmarshal(m, b)
}
func (m *ActiveState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveState.Marshal(b, m, deterministic)
}
func (dst *ActiveState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveState.Merge(dst, src)
}
func (m *ActiveState) XXX_Size() int {
	return xxx_messageInfo_ActiveState.Size(m)
}
func (m *ActiveState) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveState.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveState proto.InternalMessageInfo

func (m *ActiveState) GetPendingAttestations() []*AttestationRecord {
	if m != nil {
		return m.PendingAttestations
	}
	return nil
}

func (m *ActiveState) GetRecentBlockHashes() [][]byte {
	if m != nil {
		return m.RecentBlockHashes
	}
	return nil
}

type ValidatorRecord struct {
	PublicKey            uint64   `protobuf:"varint,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	WithdrawalShard      uint64   `protobuf:"varint,2,opt,name=withdrawal_shard,json=withdrawalShard,proto3" json:"withdrawal_shard,omitempty"`
	WithdrawalAddress    []byte   `protobuf:"bytes,3,opt,name=withdrawal_address,json=withdrawalAddress,proto3" json:"withdrawal_address,omitempty"`
	RandaoCommitment     []byte   `protobuf:"bytes,4,opt,name=randao_commitment,json=randaoCommitment,proto3" json:"randao_commitment,omitempty"`
	Balance              uint64   `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	StartDynasty         uint64   `protobuf:"varint,6,opt,name=start_dynasty,json=startDynasty,proto3" json:"start_dynasty,omitempty"`
	EndDynasty           uint64   `protobuf:"varint,7,opt,name=end_dynasty,json=endDynasty,proto3" json:"end_dynasty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorRecord) Reset()         { *m = ValidatorRecord{} }
func (m *ValidatorRecord) String() string { return proto.CompactTextString(m) }
func (*ValidatorRecord) ProtoMessage()    {}
func (*ValidatorRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{15}
}
func (m *ValidatorRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorRecord.Unmarshal(m, b)
}
func (m *ValidatorRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorRecord.Marshal(b, m, deterministic)
}
func (dst *ValidatorRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorRecord.Merge(dst, src)
}
func (m *ValidatorRecord) XXX_Size() int {
	return xxx_messageInfo_ValidatorRecord.Size(m)
}
func (m *ValidatorRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorRecord proto.InternalMessageInfo

func (m *ValidatorRecord) GetPublicKey() uint64 {
	if m != nil {
		return m.PublicKey
	}
	return 0
}

func (m *ValidatorRecord) GetWithdrawalShard() uint64 {
	if m != nil {
		return m.WithdrawalShard
	}
	return 0
}

func (m *ValidatorRecord) GetWithdrawalAddress() []byte {
	if m != nil {
		return m.WithdrawalAddress
	}
	return nil
}

func (m *ValidatorRecord) GetRandaoCommitment() []byte {
	if m != nil {
		return m.RandaoCommitment
	}
	return nil
}

func (m *ValidatorRecord) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *ValidatorRecord) GetStartDynasty() uint64 {
	if m != nil {
		return m.StartDynasty
	}
	return 0
}

func (m *ValidatorRecord) GetEndDynasty() uint64 {
	if m != nil {
		return m.EndDynasty
	}
	return 0
}

type AttestationRecord struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ShardId              uint64   `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ShardBlockHash       []byte   `protobuf:"bytes,3,opt,name=shard_block_hash,json=shardBlockHash,proto3" json:"shard_block_hash,omitempty"`
	AttesterBitfield     []byte   `protobuf:"bytes,4,opt,name=attester_bitfield,json=attesterBitfield,proto3" json:"attester_bitfield,omitempty"`
	ObliqueParentHashes  [][]byte `protobuf:"bytes,5,rep,name=oblique_parent_hashes,json=obliqueParentHashes,proto3" json:"oblique_parent_hashes,omitempty"`
	AggregateSig         []uint64 `protobuf:"varint,6,rep,packed,name=aggregate_sig,json=aggregateSig,proto3" json:"aggregate_sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttestationRecord) Reset()         { *m = AttestationRecord{} }
func (m *AttestationRecord) String() string { return proto.CompactTextString(m) }
func (*AttestationRecord) ProtoMessage()    {}
func (*AttestationRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{16}
}
func (m *AttestationRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationRecord.Unmarshal(m, b)
}
func (m *AttestationRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationRecord.Marshal(b, m, deterministic)
}
func (dst *AttestationRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationRecord.Merge(dst, src)
}
func (m *AttestationRecord) XXX_Size() int {
	return xxx_messageInfo_AttestationRecord.Size(m)
}
func (m *AttestationRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationRecord proto.InternalMessageInfo

func (m *AttestationRecord) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *AttestationRecord) GetShardId() uint64 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *AttestationRecord) GetShardBlockHash() []byte {
	if m != nil {
		return m.ShardBlockHash
	}
	return nil
}

func (m *AttestationRecord) GetAttesterBitfield() []byte {
	if m != nil {
		return m.AttesterBitfield
	}
	return nil
}

func (m *AttestationRecord) GetObliqueParentHashes() [][]byte {
	if m != nil {
		return m.ObliqueParentHashes
	}
	return nil
}

func (m *AttestationRecord) GetAggregateSig() []uint64 {
	if m != nil {
		return m.AggregateSig
	}
	return nil
}

type CrosslinkRecord struct {
	Dynasty              uint64   `protobuf:"varint,1,opt,name=dynasty,proto3" json:"dynasty,omitempty"`
	Blockhash            []byte   `protobuf:"bytes,2,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrosslinkRecord) Reset()         { *m = CrosslinkRecord{} }
func (m *CrosslinkRecord) String() string { return proto.CompactTextString(m) }
func (*CrosslinkRecord) ProtoMessage()    {}
func (*CrosslinkRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_a1c78d81bd7dacd5, []int{17}
}
func (m *CrosslinkRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrosslinkRecord.Unmarshal(m, b)
}
func (m *CrosslinkRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrosslinkRecord.Marshal(b, m, deterministic)
}
func (dst *CrosslinkRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrosslinkRecord.Merge(dst, src)
}
func (m *CrosslinkRecord) XXX_Size() int {
	return xxx_messageInfo_CrosslinkRecord.Size(m)
}
func (m *CrosslinkRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CrosslinkRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CrosslinkRecord proto.InternalMessageInfo

func (m *CrosslinkRecord) GetDynasty() uint64 {
	if m != nil {
		return m.Dynasty
	}
	return 0
}

func (m *CrosslinkRecord) GetBlockhash() []byte {
	if m != nil {
		return m.Blockhash
	}
	return nil
}

func init() {
	proto.RegisterType((*BeaconBlockHashAnnounce)(nil), "ethereum.beacon.p2p.v1.BeaconBlockHashAnnounce")
	proto.RegisterType((*BeaconBlockRequest)(nil), "ethereum.beacon.p2p.v1.BeaconBlockRequest")
	proto.RegisterType((*BeaconBlockRequestBySlotNumber)(nil), "ethereum.beacon.p2p.v1.BeaconBlockRequestBySlotNumber")
	proto.RegisterType((*BeaconBlockResponse)(nil), "ethereum.beacon.p2p.v1.BeaconBlockResponse")
	proto.RegisterType((*BeaconBlock)(nil), "ethereum.beacon.p2p.v1.BeaconBlock")
	proto.RegisterType((*CrystallizedStateHashAnnounce)(nil), "ethereum.beacon.p2p.v1.CrystallizedStateHashAnnounce")
	proto.RegisterType((*CrystallizedStateRequest)(nil), "ethereum.beacon.p2p.v1.CrystallizedStateRequest")
	proto.RegisterType((*CrystallizedStateResponse)(nil), "ethereum.beacon.p2p.v1.CrystallizedStateResponse")
	proto.RegisterType((*CrystallizedState)(nil), "ethereum.beacon.p2p.v1.CrystallizedState")
	proto.RegisterType((*ShardAndCommitteeArray)(nil), "ethereum.beacon.p2p.v1.ShardAndCommitteeArray")
	proto.RegisterType((*ActiveStateHashAnnounce)(nil), "ethereum.beacon.p2p.v1.ActiveStateHashAnnounce")
	proto.RegisterType((*ActiveStateRequest)(nil), "ethereum.beacon.p2p.v1.ActiveStateRequest")
	proto.RegisterType((*ShardAndCommittee)(nil), "ethereum.beacon.p2p.v1.ShardAndCommittee")
	proto.RegisterType((*ActiveStateResponse)(nil), "ethereum.beacon.p2p.v1.ActiveStateResponse")
	proto.RegisterType((*ActiveState)(nil), "ethereum.beacon.p2p.v1.ActiveState")
	proto.RegisterType((*ValidatorRecord)(nil), "ethereum.beacon.p2p.v1.ValidatorRecord")
	proto.RegisterType((*AttestationRecord)(nil), "ethereum.beacon.p2p.v1.AttestationRecord")
	proto.RegisterType((*CrosslinkRecord)(nil), "ethereum.beacon.p2p.v1.CrosslinkRecord")
}

func init() {
	proto.RegisterFile("proto/beacon/p2p/v1/messages.proto", fileDescriptor_messages_a1c78d81bd7dacd5)
}

var fileDescriptor_messages_a1c78d81bd7dacd5 = []byte{
	// 1127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcf, 0x6e, 0xdb, 0xc6,
	0x13, 0x86, 0x6c, 0x39, 0x89, 0x47, 0xb2, 0x65, 0xad, 0x12, 0x9b, 0x0e, 0x7e, 0xf9, 0xd9, 0x65,
	0x50, 0xc4, 0x69, 0x11, 0x0a, 0x71, 0xd0, 0x22, 0x3d, 0xca, 0x0e, 0xdc, 0xa4, 0x4d, 0x8b, 0x80,
	0x0a, 0x8a, 0x1e, 0xda, 0x12, 0x2b, 0xee, 0x48, 0xda, 0x9a, 0xe2, 0x32, 0xbb, 0x2b, 0x1b, 0xea,
	0xa1, 0xb7, 0x3e, 0x43, 0x0f, 0x7d, 0x86, 0xbe, 0x5c, 0x9f, 0xa0, 0xd8, 0x3f, 0xa2, 0x28, 0xcb,
	0x76, 0xd0, 0x1b, 0xf9, 0xcd, 0x37, 0xc3, 0x99, 0xd9, 0xd9, 0x6f, 0x08, 0x61, 0x21, 0x85, 0x16,
	0xdd, 0x01, 0xd2, 0x54, 0xe4, 0xdd, 0xe2, 0xb8, 0xe8, 0x5e, 0x3c, 0xef, 0x4e, 0x50, 0x29, 0x3a,
	0x42, 0x15, 0x59, 0x23, 0xd9, 0x45, 0x3d, 0x46, 0x89, 0xd3, 0x49, 0xe4, 0x68, 0x51, 0x71, 0x5c,
	0x44, 0x17, 0xcf, 0x1f, 0x1e, 0x8c, 0x84, 0x18, 0x65, 0xd8, 0xb5, 0xac, 0xc1, 0x74, 0xd8, 0xd5,
	0x7c, 0x82, 0x4a, 0xd3, 0x49, 0xe1, 0x1c, 0xc3, 0x67, 0xb0, 0x77, 0x62, 0x3d, 0x4e, 0x32, 0x91,
	0x9e, 0xbf, 0xa6, 0x6a, 0xdc, 0xcb, 0x73, 0x31, 0xcd, 0x53, 0x24, 0x04, 0xea, 0x63, 0xaa, 0xc6,
	0x41, 0xed, 0xb0, 0x76, 0xd4, 0x8c, 0xed, 0x73, 0x78, 0x04, 0xa4, 0x42, 0x8f, 0xf1, 0xc3, 0x14,
	0x95, 0xbe, 0x96, 0xd9, 0x83, 0xff, 0xaf, 0x32, 0x4f, 0x66, 0xfd, 0x4c, 0xe8, 0xef, 0xa7, 0x93,
	0x01, 0x4a, 0x72, 0x00, 0x0d, 0x95, 0x09, 0x9d, 0xe4, 0xf6, 0xd5, 0x3a, 0xd7, 0x63, 0x50, 0x25,
	0x21, 0x7c, 0x07, 0x9d, 0xa5, 0x10, 0xaa, 0x10, 0xb9, 0x42, 0xf2, 0x15, 0x6c, 0x0c, 0x0c, 0x60,
	0x3d, 0x1a, 0xc7, 0x8f, 0xa3, 0xeb, 0x6b, 0x8f, 0xaa, 0xbe, 0xce, 0x23, 0xfc, 0x63, 0x1d, 0x1a,
	0x15, 0xd8, 0xa4, 0x50, 0x50, 0x89, 0xb9, 0x4e, 0x2a, 0xf9, 0x83, 0x83, 0x4c, 0x2f, 0xae, 0xe6,
	0xb8, 0x76, 0x35, 0x47, 0xf2, 0x18, 0xb6, 0x24, 0xcd, 0x19, 0x15, 0x89, 0xc4, 0x0b, 0xa4, 0x59,
	0xb0, 0x6e, 0x63, 0x34, 0x1d, 0x18, 0x5b, 0x8c, 0x84, 0xb0, 0x55, 0x88, 0xcb, 0x24, 0x1d, 0x53,
	0x9e, 0x27, 0x12, 0x87, 0x41, 0xdd, 0x92, 0x1a, 0x85, 0xb8, 0x3c, 0x35, 0x58, 0x8c, 0x43, 0xf2,
	0x19, 0xb4, 0x69, 0xaa, 0xf9, 0x05, 0x26, 0x4a, 0x53, 0x8d, 0x2e, 0xa1, 0x0d, 0xcb, 0x6b, 0x39,
	0x43, 0xdf, 0xe0, 0x36, 0xab, 0x2f, 0x61, 0x2f, 0x95, 0x33, 0xa5, 0x69, 0x96, 0xf1, 0xdf, 0x90,
	0x55, 0x3d, 0xee, 0x58, 0x8f, 0x07, 0x55, 0xf3, 0xc2, 0xef, 0x25, 0x6c, 0x96, 0xe7, 0x1f, 0xdc,
	0xb5, 0xdd, 0x7b, 0x18, 0xb9, 0x09, 0x89, 0xe6, 0x13, 0x12, 0xbd, 0x9f, 0x33, 0xe2, 0x05, 0x99,
	0x7c, 0x07, 0x4d, 0xaa, 0xb5, 0x79, 0xd1, 0x5c, 0xe4, 0x2a, 0xb8, 0x77, 0xb8, 0x7e, 0xd4, 0x38,
	0x7e, 0x7a, 0x53, 0xeb, 0x7b, 0x0b, 0x6e, 0x8c, 0xa9, 0x90, 0x2c, 0x5e, 0x72, 0x0f, 0x5f, 0xc0,
	0xa3, 0xd3, 0xeb, 0x32, 0xbc, 0x75, 0xf6, 0x22, 0x08, 0x56, 0x9c, 0x6e, 0x9b, 0xc0, 0x29, 0xec,
	0x5f, 0xc3, 0xf7, 0x43, 0xf4, 0x23, 0x90, 0xd5, 0x16, 0xfa, 0x89, 0xba, 0xb1, 0xac, 0xd5, 0x70,
	0xed, 0x95, 0x46, 0x87, 0x7f, 0x6f, 0x40, 0x7b, 0x85, 0x68, 0x8e, 0x37, 0xa3, 0x4a, 0xfb, 0xa3,
	0x92, 0x98, 0xd2, 0x2c, 0xf5, 0x23, 0xdf, 0x32, 0x06, 0x9f, 0x9d, 0x81, 0xc9, 0x53, 0xd8, 0xf9,
	0x75, 0xaa, 0x34, 0x1f, 0x72, 0x9b, 0x98, 0x44, 0x7a, 0xee, 0x27, 0xaf, 0x55, 0xe2, 0x7d, 0x0b,
	0x93, 0x08, 0x3a, 0x36, 0x6c, 0x85, 0x9f, 0x09, 0x6d, 0x87, 0xb0, 0x1e, 0xdb, 0x2f, 0x7e, 0x53,
	0x7a, 0x64, 0x42, 0x97, 0xfc, 0x21, 0xcf, 0xa9, 0x2f, 0xdc, 0xf0, 0xeb, 0x0b, 0xfe, 0xd9, 0xdc,
	0x62, 0xf9, 0x4f, 0xa0, 0x95, 0x4e, 0xa5, 0xbd, 0x21, 0x6c, 0x96, 0x53, 0xa5, 0x67, 0x76, 0x26,
	0xeb, 0xf1, 0xb6, 0x87, 0x5f, 0x39, 0x94, 0xbc, 0x84, 0x20, 0x95, 0x42, 0xa9, 0x8c, 0xe7, 0xe7,
	0x3c, 0x1f, 0x99, 0x3a, 0xa5, 0x4e, 0xd4, 0x98, 0x4a, 0x66, 0x67, 0xb2, 0x1e, 0xef, 0x56, 0xed,
	0x7d, 0x63, 0xee, 0x1b, 0x2b, 0xf9, 0x14, 0xb6, 0xb5, 0xd0, 0x34, 0x4b, 0x18, 0x16, 0x42, 0x71,
	0xad, 0xec, 0x64, 0xd6, 0xe3, 0x2d, 0x8b, 0xbe, 0xf2, 0x20, 0xf9, 0x04, 0x9a, 0x3e, 0x83, 0x44,
	0x21, 0xb2, 0xe0, 0x9e, 0xbb, 0x42, 0x1e, 0xeb, 0x23, 0x32, 0xf2, 0x05, 0xec, 0x55, 0x29, 0x89,
	0xad, 0x54, 0xa2, 0x42, 0x1d, 0x6c, 0xda, 0x90, 0xf7, 0x2b, 0xec, 0xb7, 0x54, 0xe9, 0xd8, 0xd8,
	0xc8, 0x7b, 0x68, 0x97, 0xa9, 0x99, 0x93, 0x11, 0x92, 0xa9, 0x00, 0xec, 0x80, 0x3f, 0xb9, 0x79,
	0x12, 0xbc, 0x83, 0x1f, 0xef, 0x9d, 0x74, 0x19, 0x50, 0xe4, 0x6b, 0x80, 0x0b, 0x9a, 0x71, 0x46,
	0xb5, 0x90, 0x2a, 0x68, 0xdc, 0x1e, 0xee, 0x87, 0x39, 0xd3, 0x87, 0xab, 0xb8, 0x92, 0x5f, 0xa0,
	0xc3, 0x73, 0xc6, 0x53, 0x54, 0xc9, 0x50, 0xc8, 0x64, 0x8c, 0x7c, 0x34, 0xd6, 0x2a, 0x68, 0xda,
	0x88, 0xd1, 0x4d, 0x11, 0x6d, 0x6f, 0x7b, 0x39, 0x3b, 0x15, 0x93, 0x09, 0xd7, 0x1a, 0xb1, 0x27,
	0x25, 0x9d, 0xc5, 0x6d, 0x1f, 0xea, 0x4c, 0xc8, 0xd7, 0x2e, 0x50, 0xf8, 0x3b, 0xec, 0x5e, 0x4f,
	0x26, 0x0c, 0xf6, 0xa9, 0x79, 0x70, 0xc7, 0x98, 0xd0, 0x9c, 0x25, 0xe9, 0x9c, 0x11, 0xd4, 0x6e,
	0x57, 0x80, 0x95, 0x90, 0xf1, 0xae, 0x8d, 0xb5, 0x82, 0x9b, 0x0d, 0xd4, 0x5b, 0xd6, 0xb7, 0x8f,
	0x6d, 0xa0, 0x0a, 0xfd, 0xb6, 0xfb, 0xff, 0x16, 0xda, 0x2b, 0x5f, 0x23, 0xfb, 0x70, 0xcf, 0x55,
	0xc3, 0x99, 0xbf, 0x7e, 0x77, 0xed, 0xfb, 0x1b, 0x46, 0xfe, 0x07, 0x9b, 0x8b, 0xf2, 0xd6, 0x0e,
	0xd7, 0x8f, 0xb6, 0xe2, 0x05, 0x10, 0xfe, 0x0c, 0x9d, 0xa5, 0xef, 0x7a, 0x1d, 0x39, 0x83, 0x66,
	0x55, 0xb6, 0x3f, 0xb6, 0x93, 0xaa, 0x21, 0x1a, 0x15, 0x59, 0x0f, 0xff, 0xaa, 0x41, 0xa3, 0x62,
	0x24, 0x3f, 0xc1, 0xfd, 0x02, 0x73, 0x66, 0xae, 0xd2, 0x92, 0xf0, 0xd6, 0xfe, 0xab, 0xf0, 0x76,
	0x7c, 0x98, 0x8a, 0x45, 0x19, 0x19, 0x90, 0x98, 0x9a, 0x5b, 0x6d, 0xf7, 0xa2, 0x5d, 0x1d, 0xa8,
	0x6c, 0xd1, 0xcd, 0xb8, 0xed, 0x4c, 0xe5, 0x0f, 0x01, 0xaa, 0xf0, 0xcf, 0x35, 0x68, 0x5d, 0x99,
	0x51, 0xf2, 0x08, 0xa0, 0x98, 0x0e, 0x32, 0x9e, 0x26, 0xe7, 0x38, 0xf3, 0xbd, 0xdc, 0x74, 0xc8,
	0xb7, 0x38, 0x33, 0x22, 0x76, 0xc9, 0xf5, 0x98, 0x49, 0x7a, 0x49, 0x33, 0x2f, 0x04, 0x5e, 0xc4,
	0x16, 0xb8, 0x53, 0x80, 0x67, 0x40, 0x2a, 0x54, 0xca, 0x98, 0x44, 0xa5, 0xfc, 0x22, 0x6d, 0x2f,
	0x2c, 0x3d, 0x67, 0x20, 0x9f, 0x43, 0xdb, 0xaf, 0x5c, 0x77, 0x3a, 0x13, 0xcc, 0xb5, 0xdf, 0xa8,
	0x3b, 0xce, 0x70, 0x5a, 0xe2, 0x24, 0x80, 0xbb, 0x03, 0x9a, 0xd1, 0x3c, 0x45, 0x2f, 0x5c, 0xf3,
	0x57, 0xb3, 0xb9, 0x9d, 0x48, 0xcd, 0x85, 0xcd, 0xc9, 0x54, 0xd3, 0x82, 0x73, 0x59, 0x3b, 0x80,
	0x06, 0xe6, 0xac, 0xa4, 0x38, 0x65, 0x02, 0xcc, 0x99, 0x27, 0x84, 0xff, 0xd4, 0xa0, 0xbd, 0xd2,
	0x74, 0x33, 0x8e, 0x56, 0x57, 0x5d, 0x57, 0xec, 0xf3, 0xd2, 0xe4, 0xad, 0x2d, 0x4f, 0xde, 0x11,
	0xec, 0x38, 0xd3, 0xe2, 0x34, 0x7c, 0xf9, 0xdb, 0x16, 0x2f, 0x8f, 0xc2, 0xd4, 0xee, 0xc6, 0x01,
	0x65, 0x32, 0xe0, 0x7a, 0xc8, 0x31, 0x63, 0xf3, 0xda, 0xe7, 0x86, 0x13, 0x8f, 0x93, 0x63, 0x78,
	0x20, 0x06, 0x19, 0xff, 0x30, 0xc5, 0xa4, 0xf2, 0x97, 0x83, 0x2a, 0xd8, 0xb0, 0xe7, 0xdc, 0xf1,
	0xc6, 0x77, 0xe5, 0xef, 0x0e, 0x2a, 0xd3, 0x15, 0x3a, 0x1a, 0x49, 0x1c, 0x99, 0x35, 0xa5, 0xf8,
	0x28, 0xb8, 0x73, 0xb8, 0x6e, 0xba, 0x52, 0x82, 0x7d, 0x3e, 0x0a, 0xdf, 0x40, 0xeb, 0x8a, 0x00,
	0x9a, 0x3e, 0xcf, 0x9b, 0xe4, 0xaf, 0x95, 0x7f, 0x35, 0xd7, 0xca, 0x96, 0x65, 0xab, 0x5a, 0xb3,
	0xa9, 0x2e, 0x80, 0xc1, 0x1d, 0xfb, 0xdf, 0xf1, 0xe2, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e,
	0x51, 0x4f, 0xea, 0xe5, 0x0a, 0x00, 0x00,
}
