load("@prysm//tools/go:def.bzl", "go_test")

go_test(
    name = "go_default_test",
    size = "large",
    srcs = [
        "altair__epoch_processing__effective_balance_updates_test.go",
        "altair__epoch_processing__eth1_data_reset_test.go",
        "altair__epoch_processing__historical_roots_update_test.go",
        "altair__epoch_processing__inactivity_updates_test.go",
        "altair__epoch_processing__justification_and_finalization_test.go",
        "altair__epoch_processing__participation_flag_updates_test.go",
        "altair__epoch_processing__randao_mixes_reset_test.go",
        "altair__epoch_processing__registry_updates_test.go",
        "altair__epoch_processing__rewards_and_penalties_test.go",
        "altair__epoch_processing__slashings_reset_test.go",
        "altair__epoch_processing__slashings_test.go",
        "altair__finality__finality_test.go",
        "altair__fork_helper__upgrade_to_altair_test.go",
        "altair__fork_transition__transition_test.go",
        "altair__forkchoice__forkchoice_test.go",
        "altair__light_client__single_merkle_proof_test.go",
        "altair__operations__attestation_test.go",
        "altair__operations__attester_slashing_test.go",
        "altair__operations__block_header_test.go",
        "altair__operations__deposit_test.go",
        "altair__operations__proposer_slashing_test.go",
        "altair__operations__sync_committee_test.go",
        "altair__operations__voluntary_exit_test.go",
        "altair__random__random_test.go",
        "altair__rewards__rewards_test.go",
        "altair__sanity__blocks_test.go",
        "altair__sanity__slots_test.go",
        "altair__ssz_static__ssz_static_test.go",
        "bellatrix__epoch_processing__effective_balance_updates_test.go",
        "bellatrix__epoch_processing__eth1_data_reset_test.go",
        "bellatrix__epoch_processing__historical_roots_update_test.go",
        "bellatrix__epoch_processing__inactivity_updates_test.go",
        "bellatrix__epoch_processing__justification_and_finalization_test.go",
        "bellatrix__epoch_processing__participation_flag_updates_test.go",
        "bellatrix__epoch_processing__randao_mixes_reset_test.go",
        "bellatrix__epoch_processing__registry_updates_test.go",
        "bellatrix__epoch_processing__rewards_and_penalties_test.go",
        "bellatrix__epoch_processing__slashings_reset_test.go",
        "bellatrix__epoch_processing__slashings_test.go",
        "bellatrix__finality__finality_test.go",
        "bellatrix__fork_helper__upgrade_to_altair_test.go",
        "bellatrix__fork_transition__transition_test.go",
        "bellatrix__forkchoice__forkchoice_test.go",
        "bellatrix__light_client__single_merkle_proof_test.go",
        "bellatrix__operations__attestation_test.go",
        "bellatrix__operations__attester_slashing_test.go",
        "bellatrix__operations__block_header_test.go",
        "bellatrix__operations__deposit_test.go",
        "bellatrix__operations__execution_payload_test.go",
        "bellatrix__operations__proposer_slashing_test.go",
        "bellatrix__operations__sync_committee_test.go",
        "bellatrix__operations__voluntary_exit_test.go",
        "bellatrix__random__random_test.go",
        "bellatrix__rewards__rewards_test.go",
        "bellatrix__sanity__blocks_test.go",
        "bellatrix__sanity__slots_test.go",
        "bellatrix__ssz_static__ssz_static_test.go",
        "capella__epoch_processing__effective_balance_updates_test.go",
        "capella__epoch_processing__eth1_data_reset_test.go",
        "capella__epoch_processing__historical_summaries_update_test.go",
        "capella__epoch_processing__inactivity_updates_test.go",
        "capella__epoch_processing__justification_and_finalization_test.go",
        "capella__epoch_processing__participation_flag_updates_test.go",
        "capella__epoch_processing__randao_mixes_reset_test.go",
        "capella__epoch_processing__registry_updates_test.go",
        "capella__epoch_processing__rewards_and_penalties_test.go",
        "capella__epoch_processing__slashings_reset_test.go",
        "capella__epoch_processing__slashings_test.go",
        "capella__finality__finality_test.go",
        "capella__fork_helper__upgrade_to_capella_test.go",
        "capella__fork_transition__transition_test.go",
        "capella__forkchoice__forkchoice_test.go",
        "capella__light_client__single_merkle_proof_test.go",
        "capella__operations__attestation_test.go",
        "capella__operations__attester_slashing_test.go",
        "capella__operations__block_header_test.go",
        "capella__operations__bls_to_execution_change_test.go",
        "capella__operations__deposit_test.go",
        "capella__operations__execution_payload_test.go",
        "capella__operations__proposer_slashing_test.go",
        "capella__operations__sync_committee_test.go",
        "capella__operations__voluntary_exit_test.go",
        "capella__operations__withdrawals_test.go",
        "capella__random__random_test.go",
        "capella__rewards__rewards_test.go",
        "capella__sanity__blocks_test.go",
        "capella__sanity__slots_test.go",
        "capella__ssz_static__ssz_static_test.go",
        "deneb__epoch_processing__effective_balance_updates_test.go",
        "deneb__epoch_processing__eth1_data_reset_test.go",
        "deneb__epoch_processing__historical_summaries_update_test.go",
        "deneb__epoch_processing__inactivity_updates_test.go",
        "deneb__epoch_processing__justification_and_finalization_test.go",
        "deneb__epoch_processing__participation_flag_updates_test.go",
        "deneb__epoch_processing__randao_mixes_reset_test.go",
        "deneb__epoch_processing__registry_updates_test.go",
        "deneb__epoch_processing__rewards_and_penalties_test.go",
        "deneb__epoch_processing__slashings_reset_test.go",
        "deneb__epoch_processing__slashings_test.go",
        "deneb__finality__finality_test.go",
        "deneb__fork_helper__upgrade_to_deneb_test.go",
        "deneb__fork_transition__transition_test.go",
        "deneb__forkchoice__forkchoice_test.go",
        "deneb__light_client__single_merkle_proof_test.go",
        "deneb__merkle_proof__merkle_proof_test.go",
        "deneb__operations__attestation_test.go",
        "deneb__operations__attester_slashing_test.go",
        "deneb__operations__block_header_test.go",
        "deneb__operations__bls_to_execution_change_test.go",
        "deneb__operations__deposit_test.go",
        "deneb__operations__execution_payload_test.go",
        "deneb__operations__proposer_slashing_test.go",
        "deneb__operations__sync_committee_test.go",
        "deneb__operations__voluntary_exit_test.go",
        "deneb__operations__withdrawals_test.go",
        "deneb__random__random_test.go",
        "deneb__rewards__rewards_test.go",
        "deneb__sanity__blocks_test.go",
        "deneb__sanity__slots_test.go",
        "deneb__ssz_static__ssz_static_test.go",
        "electra__epoch_processing__effective_balance_updates_test.go",
        "electra__epoch_processing__eth1_data_reset_test.go",
        "electra__epoch_processing__historical_summaries_update_test.go",
        "electra__epoch_processing__inactivity_updates_test.go",
        "electra__epoch_processing__justification_and_finalization_test.go",
        "electra__epoch_processing__participation_flag_updates_test.go",
        "electra__epoch_processing__pending_consolidations_test.go",
        "electra__epoch_processing__pending_deposits_updates_test.go",
        "electra__epoch_processing__randao_mixes_reset_test.go",
        "electra__epoch_processing__registry_updates_test.go",
        "electra__epoch_processing__rewards_and_penalties_test.go",
        "electra__epoch_processing__slashings_reset_test.go",
        "electra__epoch_processing__slashings_test.go",
        "electra__finality__finality_test.go",
        "electra__fork_helper__upgrade_to_electra_test.go",
        "electra__fork_transition__transition_test.go",
        "electra__forkchoice__forkchoice_test.go",
        "electra__light_client__single_merkle_proof_test.go",
        "electra__merkle_proof__merkle_proof_test.go",
        "electra__operations__attestation_test.go",
        "electra__operations__attester_slashing_test.go",
        "electra__operations__block_header_test.go",
        "electra__operations__bls_to_execution_change_test.go",
        "electra__operations__consolidation_test.go",
        "electra__operations__deposit_requests_test.go",
        "electra__operations__deposit_test.go",
        "electra__operations__execution_layer_withdrawals_test.go",
        "electra__operations__execution_payload_test.go",
        "electra__operations__proposer_slashing_test.go",
        "electra__operations__sync_committee_test.go",
        "electra__operations__voluntary_exit_test.go",
        "electra__operations__withdrawals_test.go",
        "electra__random__random_test.go",
        "electra__rewards__rewards_test.go",
        "electra__sanity__blocks_test.go",
        "electra__sanity__slots_test.go",
        "electra__ssz_static__ssz_static_test.go",
        "fulu__epoch_processing__effective_balance_updates_test.go",
        "fulu__epoch_processing__eth1_data_reset_test.go",
        "fulu__epoch_processing__historical_summaries_update_test.go",
        "fulu__epoch_processing__inactivity_updates_test.go",
        "fulu__epoch_processing__justification_and_finalization_test.go",
        "fulu__epoch_processing__participation_flag_updates_test.go",
        "fulu__epoch_processing__pending_consolidations_test.go",
        "fulu__epoch_processing__pending_deposits_updates_test.go",
        "fulu__epoch_processing__proposer_lookahead_test.go",
        "fulu__epoch_processing__randao_mixes_reset_test.go",
        "fulu__epoch_processing__registry_updates_test.go",
        "fulu__epoch_processing__rewards_and_penalties_test.go",
        "fulu__epoch_processing__slashings_reset_test.go",
        "fulu__epoch_processing__slashings_test.go",
        "fulu__finality__finality_test.go",
        "fulu__fork__upgrade_to_fulu_test.go",
        "fulu__fork_transition__transition_test.go",
        "fulu__forkchoice__forkchoice_test.go",
        "fulu__light_client__single_merkle_proof_test.go",
        "fulu__merkle_proof__merkle_proof_test.go",
        "fulu__networking__custody_groups_test.go",
        "fulu__operations__attestation_test.go",
        "fulu__operations__attester_slashing_test.go",
        "fulu__operations__block_header_test.go",
        "fulu__operations__bls_to_execution_change_test.go",
        "fulu__operations__consolidation_test.go",
        "fulu__operations__deposit_requests_test.go",
        "fulu__operations__execution_layer_withdrawals_test.go",
        "fulu__operations__execution_payload_test.go",
        "fulu__operations__proposer_slashing_test.go",
        "fulu__operations__sync_committee_test.go",
        "fulu__operations__voluntary_exit_test.go",
        "fulu__operations__withdrawals_test.go",
        "fulu__random__random_test.go",
        "fulu__rewards__rewards_test.go",
        "fulu__sanity__blocks_test.go",
        "fulu__sanity__slots_test.go",
        "fulu__ssz_static__ssz_static_test.go",
        "phase0__epoch_processing__effective_balance_updates_test.go",
        "phase0__epoch_processing__epoch_processing_test.go",
        "phase0__epoch_processing__eth1_data_reset_test.go",
        "phase0__epoch_processing__historical_roots_update_test.go",
        "phase0__epoch_processing__justification_and_finalization_test.go",
        "phase0__epoch_processing__participation_record_updates_test.go",
        "phase0__epoch_processing__randao_mixes_reset_test.go",
        "phase0__epoch_processing__registry_updates_test.go",
        "phase0__epoch_processing__rewards_and_penalties_test.go",
        "phase0__epoch_processing__slashings_reset_test.go",
        "phase0__epoch_processing__slashings_test.go",
        "phase0__finality__finality_test.go",
        "phase0__operations__attestation_test.go",
        "phase0__operations__attester_slashing_test.go",
        "phase0__operations__block_header_test.go",
        "phase0__operations__deposit_test.go",
        "phase0__operations__proposer_slashing_test.go",
        "phase0__operations__voluntary_exit_test.go",
        "phase0__random__random_test.go",
        "phase0__rewards__rewards_test.go",
        "phase0__sanity__blocks_test.go",
        "phase0__sanity__slots_test.go",
        "phase0__shuffling__core_shuffle_test.go",
        "phase0__ssz_static__ssz_static_test.go",
    ],
    data = ["@consensus_spec_tests//:test_data"],
    tags = ["spectest"],
    deps = [
        "//config/params:go_default_library",
        "//runtime/version:go_default_library",
        "//testing/spectest/shared/altair/epoch_processing:go_default_library",
        "//testing/spectest/shared/altair/finality:go_default_library",
        "//testing/spectest/shared/altair/fork:go_default_library",
        "//testing/spectest/shared/altair/operations:go_default_library",
        "//testing/spectest/shared/altair/rewards:go_default_library",
        "//testing/spectest/shared/altair/sanity:go_default_library",
        "//testing/spectest/shared/altair/ssz_static:go_default_library",
        "//testing/spectest/shared/bellatrix/epoch_processing:go_default_library",
        "//testing/spectest/shared/bellatrix/finality:go_default_library",
        "//testing/spectest/shared/bellatrix/fork:go_default_library",
        "//testing/spectest/shared/bellatrix/operations:go_default_library",
        "//testing/spectest/shared/bellatrix/rewards:go_default_library",
        "//testing/spectest/shared/bellatrix/sanity:go_default_library",
        "//testing/spectest/shared/bellatrix/ssz_static:go_default_library",
        "//testing/spectest/shared/capella/epoch_processing:go_default_library",
        "//testing/spectest/shared/capella/finality:go_default_library",
        "//testing/spectest/shared/capella/fork:go_default_library",
        "//testing/spectest/shared/capella/operations:go_default_library",
        "//testing/spectest/shared/capella/rewards:go_default_library",
        "//testing/spectest/shared/capella/sanity:go_default_library",
        "//testing/spectest/shared/capella/ssz_static:go_default_library",
        "//testing/spectest/shared/common/forkchoice:go_default_library",
        "//testing/spectest/shared/common/light_client:go_default_library",
        "//testing/spectest/shared/deneb/epoch_processing:go_default_library",
        "//testing/spectest/shared/deneb/finality:go_default_library",
        "//testing/spectest/shared/deneb/fork:go_default_library",
        "//testing/spectest/shared/deneb/merkle_proof:go_default_library",
        "//testing/spectest/shared/deneb/operations:go_default_library",
        "//testing/spectest/shared/deneb/rewards:go_default_library",
        "//testing/spectest/shared/deneb/sanity:go_default_library",
        "//testing/spectest/shared/deneb/ssz_static:go_default_library",
        "//testing/spectest/shared/electra/epoch_processing:go_default_library",
        "//testing/spectest/shared/electra/finality:go_default_library",
        "//testing/spectest/shared/electra/fork:go_default_library",
        "//testing/spectest/shared/electra/merkle_proof:go_default_library",
        "//testing/spectest/shared/electra/operations:go_default_library",
        "//testing/spectest/shared/electra/rewards:go_default_library",
        "//testing/spectest/shared/electra/sanity:go_default_library",
        "//testing/spectest/shared/electra/ssz_static:go_default_library",
        "//testing/spectest/shared/fulu/epoch_processing:go_default_library",
        "//testing/spectest/shared/fulu/finality:go_default_library",
        "//testing/spectest/shared/fulu/fork:go_default_library",
        "//testing/spectest/shared/fulu/merkle_proof:go_default_library",
        "//testing/spectest/shared/fulu/networking:go_default_library",
        "//testing/spectest/shared/fulu/operations:go_default_library",
        "//testing/spectest/shared/fulu/rewards:go_default_library",
        "//testing/spectest/shared/fulu/sanity:go_default_library",
        "//testing/spectest/shared/fulu/ssz_static:go_default_library",
        "//testing/spectest/shared/phase0/epoch_processing:go_default_library",
        "//testing/spectest/shared/phase0/finality:go_default_library",
        "//testing/spectest/shared/phase0/operations:go_default_library",
        "//testing/spectest/shared/phase0/rewards:go_default_library",
        "//testing/spectest/shared/phase0/sanity:go_default_library",
        "//testing/spectest/shared/phase0/shuffling/core/shuffle:go_default_library",
        "//testing/spectest/shared/phase0/ssz_static:go_default_library",
    ],
)
