package main

var foods = []string{
	"Bahn Mi",
	"Baked Beans",
	"Banana Pudding",
	"Beef Bourguignon",
	"Bibimbap",
	"Biryani",
	"Bulgogi",
	"Burger",
	"Burrito",
	"Calzone",
	"Catfish Fry",
	"Ceviche",
	"Chicken Sandwich",
	"Chicken Satay",
	"Chicken Tendies",
	"Chicken Wings",
	"Chow Fun",
	"Cold Pizza :pizza:",
	"Cuban Sandwich",
	"Doner Kebab",
	"Fajitas",
	"Falafel",
	"Fish and Chips",
	"Fish Tacos",
	"Fried Chicken",
	"Fried Eggs",
	"Fried Rice",
	"Fries",
	"Grilled Cheese",
	"Gumbo",
	"Gyro",
	"Gyoza",
	"Hash Browns",
	"Hotpot",
	"Hush Puppies",
	"Japanese Curry",
	"Jerk Chicken",
	"Lasagna",
	"Mac & Cheese",
	"Chicken Tikka",
	"Massaman Curry",
	"Peking Duck",
	"Pita with Hummus",
	"Mexican Sandwich",
	"Orange Chicken",
	"Pad Thai",
	"Paella",
	"Parfait",
	"Pho",
	"Pierogis",
	"Pizza",
	"Po' boy",
	"Poke Bowl",
	"Quesadilla",
	"Ramen",
	"Ribeye",
	"Ribs",
	"Rissoto",
	"Salad",
	"Sandwich",
	"Scrambled Eggs",
	"Soup",
	"Steak",
	"Spaghetti",
	"Spring Rolls",
	"Stromboli",
	"Sushi",
	"Tacos",
	"Tamales",
	"Tandoori Chicken",
	"Tempura",
	"Teriyaki Chicken",
	"Tilapia With Jasmine Rice",
	"Tonkatsu",
	"Venezuelan Arepas",
	"Wrap",
	"Wings",
	"Wonton Soup",
	"Yakitori",
}

var restaurants = []string{
	"Alehouse",
	"BurgerFi",
	"Carls Jr",
	"Checkers",
	"Chick-fil-a",
	"Chili's",
	"Chipotle",
	"Crackerbarrel",
	"Cuban Guys",
	"Dennys",
	"Dominos",
	"Firehouse Subs",
	"Hardy's",
	"in-n-out",
	"Jimmy Johns",
	"KFC",
	"La Carreta",
	"Los Verdes",
	"MOD Pizza",
	"Moe's",
	"Olive Garden",
	"Panda Express",
	"Panera Bread",
	"Papa Johns",
	"PDQ",
	"Pei Wei",
	"PF Changs",
	"Pizza Hut",
	"Pollo Tropical",
	"Popeye's",
	"Sergio's",
	"Sonic",
	"Steak and Shake",
	"Subway",
	"Taco Bell",
	"TGI Fridays",
	"Wawas",
	"Wendys",
	"What-a-burger",
	"Zaxby's",
}
