syntax = "proto3";

package ethereum.engine.v1;

import "proto/eth/ext/options.proto";
import "proto/engine/v1/execution_engine.proto";
import "proto/engine/v1/electra.proto";
import "proto/engine/v1/gloas.proto";

option csharp_namespace = "Ethereum.Engine.V1";
option go_package = "github.com/OffchainLabs/prysm/v7/proto/engine/v1;enginev1";
option java_multiple_files = true;
option java_outer_classname = "ElectraProto";
option java_package = "org.ethereum.engine.v1";
option php_namespace = "Ethereum\\Engine\\v1";

message ExecutionBundleFulu {
  ExecutionPayloadDeneb payload = 1;
  bytes value = 2;
  BlobsBundleV2 blobs_bundle = 3;
  bool should_override_builder = 4;
  repeated bytes execution_requests = 5;
}

message NewPayloadRequest {
  ExecutionPayloadDeneb execution_payload = 1;

  repeated bytes versioned_hashes = 2 [
    (ethereum.eth.ext.ssz_size) = "?,32",
    (ethereum.eth.ext.ssz_max) = "4096"
  ];

  bytes parent_block_root = 3 [ (ethereum.eth.ext.ssz_size) = "32" ];
  ExecutionRequestsGloas execution_requests = 4;
}

message ExecutionBundleGloas {
  ExecutionPayloadGloas payload = 1;
  bytes value = 2;
  BlobsBundleV2 blobs_bundle = 3;
  bool should_override_builder = 4;
  repeated bytes execution_requests = 5;
}
