load("@prysm//tools/go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "doc.go",
        "ranges.go",
        "slice.go",
    ],
    importpath = "github.com/OffchainLabs/prysm/v7/container/slice",
    visibility = ["//visibility:public"],
    deps = ["//consensus-types/primitives:go_default_library"],
)

go_test(
    name = "go_default_test",
    size = "small",
    srcs = [
        "ranges_test.go",
        "slice_test.go",
    ],
    deps = [
        ":go_default_library",
        "//consensus-types/primitives:go_default_library",
        "//testing/require:go_default_library",
    ],
)
