load("@prysm//tools/go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "converts.go",
        "metadata.go",
        "node_connection.go",
    ],
    importpath = "github.com/OffchainLabs/prysm/v7/validator/helpers",
    visibility = ["//visibility:public"],
    deps = [
        "//api/grpc:go_default_library",
        "//api/rest:go_default_library",
        "//config/fieldparams:go_default_library",
        "//consensus-types/primitives:go_default_library",
        "//validator/db/iface:go_default_library",
        "//validator/slashing-protection-history/format:go_default_library",
        "@com_github_pkg_errors//:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = [
        "converts_test.go",
        "metadata_test.go",
        "node_connection_test.go",
    ],
    embed = [":go_default_library"],
    deps = [
        "//api/grpc:go_default_library",
        "//api/rest:go_default_library",
        "//config/fieldparams:go_default_library",
        "//config/proposer:go_default_library",
        "//consensus-types/interfaces:go_default_library",
        "//consensus-types/primitives:go_default_library",
        "//proto/prysm/v1alpha1:go_default_library",
        "//testing/assert:go_default_library",
        "//testing/require:go_default_library",
        "//validator/db/common:go_default_library",
        "//validator/db/iface:go_default_library",
        "//validator/slashing-protection-history/format:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
    ],
)
